/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth.index'
import { Route as AuthUsersRouteImport } from './routes/_auth.users'
import { Route as AuthSettingsRouteImport } from './routes/_auth.settings'
import { Route as AuthModerateRouteImport } from './routes/_auth.moderate'
import { Route as AuthHistoryRouteImport } from './routes/_auth.history'
import { Route as AuthArticlesRouteImport } from './routes/_auth.articles'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersRoute = AuthUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthModerateRoute = AuthModerateRouteImport.update({
  id: '/moderate',
  path: '/moderate',
  getParentRoute: () => AuthRoute,
} as any)
const AuthHistoryRoute = AuthHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthRoute,
} as any)
const AuthArticlesRoute = AuthArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/articles': typeof AuthArticlesRoute
  '/history': typeof AuthHistoryRoute
  '/moderate': typeof AuthModerateRoute
  '/settings': typeof AuthSettingsRoute
  '/users': typeof AuthUsersRoute
  '/': typeof AuthIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/articles': typeof AuthArticlesRoute
  '/history': typeof AuthHistoryRoute
  '/moderate': typeof AuthModerateRoute
  '/settings': typeof AuthSettingsRoute
  '/users': typeof AuthUsersRoute
  '/': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/articles': typeof AuthArticlesRoute
  '/_auth/history': typeof AuthHistoryRoute
  '/_auth/moderate': typeof AuthModerateRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/users': typeof AuthUsersRoute
  '/_auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/articles'
    | '/history'
    | '/moderate'
    | '/settings'
    | '/users'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/articles'
    | '/history'
    | '/moderate'
    | '/settings'
    | '/users'
    | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/articles'
    | '/_auth/history'
    | '/_auth/moderate'
    | '/_auth/settings'
    | '/_auth/users'
    | '/_auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users': {
      id: '/_auth/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/moderate': {
      id: '/_auth/moderate'
      path: '/moderate'
      fullPath: '/moderate'
      preLoaderRoute: typeof AuthModerateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/history': {
      id: '/_auth/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthHistoryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/articles': {
      id: '/_auth/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof AuthArticlesRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthArticlesRoute: typeof AuthArticlesRoute
  AuthHistoryRoute: typeof AuthHistoryRoute
  AuthModerateRoute: typeof AuthModerateRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthUsersRoute: typeof AuthUsersRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthArticlesRoute: AuthArticlesRoute,
  AuthHistoryRoute: AuthHistoryRoute,
  AuthModerateRoute: AuthModerateRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthUsersRoute: AuthUsersRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
