config:
  aws:region: ap-southeast-2
  comments:db-username: root
  comments:db-name: commentsdb
  comments:domain: codebykieran.com
  comments:subdomain: api
  comments:db-password:
    secure: AAABAF8B7XEXxTF6PyZbmOTUGznYb6oBo5NfF+CY0u07kwT1yjM8t7keaQk/O6U=
  comments:api-key:
    secure: AAABAAykhYE4rVX5EtUgsmjIRGmOOP4S2rvY2BlHudlInG5qx5YFVeoEOw==
