// Any comment matching the words in this list will be automatically flagged for review
export const flaggedWords = [
    '69',
    '88',
    '420',
    '14 words',
    'acab',
    'akia',
    'back door',
    'backseat',
    'balls',
    'bareback',
    'bdsm',
    'bi-sexual',
    'big black',
    'bisexual',
    'bit.ly',
    'black out',
    'blackout',
    'bloody',
    'bondage',
    'breivik',
    'charles martel',
    'chirst',
    'chwdp',
    'clickhere',
    'click here',
    'clitoris',
    'cocky',
    'colored people',
    'condom',
    'copy and paste',
    'coward',
    'crisis actor',
    'd-o-t com',
    'dick',
    'domination',
    'dominatrix',
    'dot co.uk',
    'dot com',
    'dot info',
    'dot ly',
    'dot net',
    'dot org',
    'dotcom',
    'dotnet',
    'dotorg',
    'drag queen',
    'dragqueen',
    'dylan roof',
    'ebba akerlund',
    'escort',
    'fagin',
    'fairy',
    'free for all',
    'freeze peach',
    'freezepeach',
    'frozen peaches',
    'fuhrer',
    'gab',
    'get a rope',
    'girl on',
    'glazed donut',
    'gmail',
    'go to hell',
    'gooch',
    'gynocrat',
    'hard core',
    'hardcore',
    'heil',
    'her period',
    'homo',
    'http:',
    'https:',
    'illuminati',
    'jesus',
    'jew',
    'john hunyadi',
    'kumquat',
    'lesbian',
    'like you',
    'loaded gun',
    'lolita',
    'mein kampf',
    'missionary',
    'mod',
    'mulatto',
    'murder',
    'my latest',
    'neo-nazi',
    'neonazi',
    'nipples',
    'noose',
    'npc',
    'nsfw',
    'nude',
    'nudity',
    'orgasm',
    'orgy',
    'pansy',
    'paycheck',
    'pearl necklace',
    'peep show',
    'penis',
    'pimp',
    'pirate bay',
    'playboy',
    'playgirl',
    'porn',
    'prick',
    'prostitute',
    'put a bullet',
    'race traitor',
    'rape',
    'raping',
    'rapist',
    'reconquista',
    'red light',
    's hit',
    'satan',
    'screw',
    'sex toy',
    'sexy',
    'shithole',
    'snatch',
    'sniper',
    'snowflakes',
    'sob',
    'spread your',
    'stormfront',
    'suicide',
    'swallow',
    'swastika',
    't.d.s.',
    'tds',
    'tee dee ess',
    'teez',
    'terrorist',
    'testicle',
    'tied up',
    'to you',
    'tongue',
    'tours 732',
    'two on one',
    'wad',
    'work online',
    'wife basher',
    'wpww',
]

// Any comment matching the words in this list will be automatically rejected
export const rejectedWords = [
    '@aol.com',
    '@gmail.com',
    '@hotmail.com',
    '@mail.com',
    '@outlook.com',
    '@ssholes',
    '@sss',
    '@yahoo.com',
    '*d-oosh*',
    '*fuck',
    '*shithole',
    '🖕',
    '$h!t',
    '$hit',
    '14-88',
    '14/23',
    '2 girls 1 cup',
    '40960',
    '23/16',
    '2g1c',
    '33/6',
    '3rd eye',
    '3rd leg',
    '3rdeye',
    '3rdleg',
    '3some',
    '4r5e',
    '4twenty',
    '5h1t',
    '5hit',
    '60 nine',
    'a_hole',
    'a_s_sers',
    'a_s_serz',
    'a_s_ses',
    'a_s_sez',
    'a_s_sing',
    'a_s_srs',
    'a_s_srz',
    'a_s_ss',
    'a_s_sz',
    'a-holes',
    'a-holez',
    'a-n-c-h-o-r',
    'a.c.a.b.',
    'a.nch.or babies',
    'a.nch.or baby',
    'a$$h0!es',
    'a$$h01es',
    'a$$h0les',
    'a55ers',
    'a55erz',
    'a55es',
    'a55ez',
    'a55holes',
    'a55ing',
    'a55rs',
    'a55rz',
    'a55s',
    'a55z',
    'acab',
    'acrotomophilia',
    'aholes',
    'aholez',
    'alabama hot pocket',
    'alaskan pipeline',
    'alex albracht',
    'alian',
    'americanthinker',
    'anal annie',
    'anal sex',
    'analannie',
    'analsex',
    'anch0r',
    'anchor babies',
    'anchor baby',
    'anilingus',
    'anus',
    'apeshit',
    'ar5e',
    'arrse',
    'arsehole',
    'ass bagger',
    'ass bags',
    'ass bandits',
    'ass bangers',
    'ass bites',
    'ass blaster',
    'ass clowns',
    'ass cocks',
    'ass cowboy',
    'ass crackers',
    'ass faces',
    'ass fuckers',
    'ass fucks',
    'ass fukkas',
    'ass goblins',
    'ass hats',
    'ass heads',
    'ass holess',
    'ass hoppers',
    'ass hore',
    'ass jabbers',
    'ass jackers',
    'ass jockey',
    'ass kisser',
    'ass klown',
    'ass lickers',
    'ass licks',
    'ass lover',
    'ass man',
    'ass monkeys',
    'ass munchers',
    'ass munchs',
    'ass niggers',
    'ass packer',
    'ass pirates',
    'ass puppies',
    'ass ranger',
    'ass shits',
    'ass suckers',
    'ass wads',
    'ass wholes',
    'ass whore',
    'ass wipes',
    'ass-fuckerers',
    'ass-fuckererz',
    'ass-fuckeres',
    'ass-fuckerez',
    'ass-fuckering',
    'ass-fuckerrs',
    'ass-fuckerrz',
    'ass-fuckerz',
    'ass-haters',
    'ass-haterz',
    'ass-hates',
    'ass-hatez',
    'ass-hating',
    'ass-hatrs',
    'ass-hatrz',
    'ass-hatz',
    'ass-jabberers',
    'ass-jabbererz',
    'ass-jabberes',
    'ass-jabberez',
    'ass-jabbering',
    'ass-jabberrs',
    'ass-jabberrz',
    'ass-jabberz',
    'ass-pirateers',
    'ass-pirateerz',
    'ass-piratees',
    'ass-pirateez',
    'ass-pirateing',
    'ass-piraters',
    'ass-piraterz',
    'ass-piratez',
    'assbagers',
    'assbagerz',
    'assbages',
    'assbagez',
    'assbagger',
    'assbaging',
    'assbagrs',
    'assbagrz',
    'assbags',
    'assbagz',
    'assbanditers',
    'assbanditerz',
    'assbandites',
    'assbanditez',
    'assbanditing',
    'assbanditrs',
    'assbanditrz',
    'assbandits',
    'assbanditz',
    'assbangeds',
    'assbangerers',
    'assbangererz',
    'assbangeres',
    'assbangerez',
    'assbangering',
    'assbangerrs',
    'assbangerrz',
    'assbangers',
    'assbangerz',
    'assbangss',
    'assbiteers',
    'assbiteerz',
    'assbitees',
    'assbiteez',
    'assbiteing',
    'assbiters',
    'assbiterz',
    'assbites',
    'assbitez',
    'assblaster',
    'assc0ckers',
    'assc0ckerz',
    'assc0ckes',
    'assc0ckez',
    'assc0cking',
    'assc0ckrs',
    'assc0ckrz',
    'assc0cks',
    'assc0ckz',
    'asscl0wners',
    'asscl0wnerz',
    'asscl0wnes',
    'asscl0wnez',
    'asscl0wning',
    'asscl0wnrs',
    'asscl0wnrz',
    'asscl0wns',
    'asscl0wnz',
    'assclowns',
    'asscocks',
    'asscowboy',
    'asscrackerers',
    'asscrackererz',
    'asscrackeres',
    'asscrackerez',
    'asscrackering',
    'asscrackerrs',
    'asscrackerrz',
    'asscrackers',
    'asscrackerz',
    'assface',
    'assfucker',
    'assfukka',
    'assgoblin',
    'asshats',
    'asshead',
    'assholes',
    'asshopper',
    'asshore',
    'assjacker',
    'assjockey',
    'asskisser',
    'assklown',
    'asslicker',
    'asslover',
    'assman',
    'assmonkey',
    'assmucus',
    'assmuncher',
    'assnigger',
    'asspacker',
    'asspirate',
    'asspuppies',
    'assranger',
    'assshit',
    'assshole',
    'asssucker',
    'asswad',
    'asswhole',
    'asswhore',
    'asswipes',
    'at gmail',
    'at hotmail',
    'athletes foot',
    'athletesfoot',
    'auto erotic',
    'autoerotic',
    'axing the weasel',
    'azzes',
    'b hard',
    'b!tch',
    'b*tt hurt',
    'b*tthurt',
    'b00bs',
    'b17ch',
    'b1tches',
    'baby batter',
    'baby juice',
    'back door man',
    'backdoorman',
    'bad ass',
    'bad fuck',
    'badfuck',
    'bagoshit',
    'ball gag',
    'ball gravy',
    'ball licker',
    'ball licking',
    'ball sack',
    'ball sucking',
    'ballbag',
    'balllicker',
    'ballsack',
    'bangbros',
    'banging',
    'barely legal',
    'barelylegal',
    'barenaked',
    'barf face',
    'barface',
    'barfface',
    'bastardo',
    'bastinado',
    'batsh*t',
    'batshit',
    'bazongas',
    'bazooms',
    'bbw',
    'beaners',
    'beastality',
    'beastiality',
    'beat your meat',
    'beatoff',
    'beatyourmeat',
    'beaver cleaver',
    'beaver lips',
    'beeyotch',
    'bestiality',
    'bi+ch',
    'bic snood',
    'big ass',
    'big bitch',
    'big breasts',
    'big butt',
    'big knockers',
    'big tits',
    'bigass',
    'bigbastard',
    'bigbutt',
    'billary',
    'billery',
    'billiary',
    'billlary',
    'billlery',
    'billllary',
    'bimbos',
    'biotch',
    'birdlock',
    '🅱️itch',
    'bitchass',
    'bitched',
    'bitchsoyboy',
    'bitchtits',
    'bitchy',
    'bite me',
    'biteme',
    'bix nood',
    'black cock',
    'black fellows',
    'blonde on blonde action',
    'blow job',
    'blow me',
    'blow your load',
    'blowjobs',
    'blue waffle',
    'blumpkin',
    'blut und ehre',
    'bm',
    'boiolas',
    'bollocks',
    'bollok',
    'bong',
    'boobies',
    'boobs',
    'boody',
    'booobs',
    'boooobs',
    'booooobs',
    'booooooobs',
    'boot party',
    'booty call',
    'breast job',
    'breast lover',
    'breast man',
    'breastjob',
    'breastlover',
    'breastman',
    'brotherfucker',
    'brown showers',
    'brunette action',
    'bu++ hurt',
    'buceta',
    'bugger',
    'bukkake',
    'bull crap',
    'bull dike',
    'bull dyke',
    'bull shit',
    'bull$*',
    'bullcrap',
    'bulldike',
    'bulldyke',
    'bullet vibe',
    'bullsch*',
    'bullsh!t',
    'bullsh1*',
    'bullshii*',
    'bullshite',
    'bullshitt',
    'bumble fuck',
    'bumblefuck',
    'bumfuck',
    'bung hole',
    'bunghole',
    'bunny fucker',
    'busty',
    'butch babes',
    'butch dike',
    'butch dyke',
    'butchbabes',
    'butchdike',
    'butchdyke',
    'butt bang',
    'butt fuckers',
    'butt head',
    'butt hurt',
    'butt man',
    'butt plug',
    'butt sore',
    'butt stain',
    'butt-pirate',
    'buttbang',
    'buttcheeks',
    'buttface',
    'buttfucka',
    'buttfuckers',
    'butthead',
    'butthole',
    'butthurt',
    'buttman',
    'buttmunch',
    'buttpirate',
    'buttplug',
    'buttsore',
    'buttstain',
    'c.o.m',
    'c.u.n.t',
    'c*nt',
    'c00ners',
    'c00nerz',
    'c00nes',
    'c00nez',
    'c00ning',
    'c00nrs',
    'c00nrz',
    'c00ns',
    'c00nz',
    'c0ck suckers',
    'c0ck-suckerers',
    'c0ck-suckererz',
    'c0ck-suckeres',
    'c0ck-suckerez',
    'c0ck-suckering',
    'c0ck-suckerrs',
    'c0ck-suckerrz',
    'c0ck-suckerz',
    'c0ckassers',
    'c0ckasserz',
    'c0ckasses',
    'c0ckassez',
    'c0ckassing',
    'c0ckassrs',
    'c0ckassrz',
    'c0ckasss',
    'c0ckassz',
    'c0ckbiteers',
    'c0ckbiteerz',
    'c0ckbitees',
    'c0ckbiteez',
    'c0ckbiteing',
    'c0ckbiters',
    'c0ckbiterz',
    'c0ckbites',
    'c0ckbitez',
    'c0ckburgerers',
    'c0ckburgererz',
    'c0ckburgeres',
    'c0ckburgerez',
    'c0ckburgering',
    'c0ckburgerrs',
    'c0ckburgerrz',
    'c0ckburgers',
    'c0ckburgerz',
    'c0ckfaceers',
    'c0ckfaceerz',
    'c0ckfacees',
    'c0ckfaceez',
    'c0ckfaceing',
    'c0ckfacers',
    'c0ckfacerz',
    'c0ckfaces',
    'c0ckfacez',
    'c0ckfuckerers',
    'c0ckfuckererz',
    'c0ckfuckeres',
    'c0ckfuckerez',
    'c0ckfuckering',
    'c0ckfuckerrs',
    'c0ckfuckerrz',
    'c0ckfuckers',
    'c0ckfuckerz',
    'c0ckheaders',
    'c0ckheaderz',
    'c0ckheades',
    'c0ckheadez',
    'c0ckheading',
    'c0ckheadrs',
    'c0ckheadrz',
    'c0ckheads',
    'c0ckheadz',
    'c0ckj0ckeyers',
    'c0ckj0ckeyerz',
    'c0ckj0ckeyes',
    'c0ckj0ckeyez',
    'c0ckj0ckeying',
    'c0ckj0ckeyrs',
    'c0ckj0ckeyrz',
    'c0ckj0ckeys',
    'c0ckj0ckeyz',
    'c0ckkn0kerers',
    'c0ckkn0kererz',
    'c0ckkn0keres',
    'c0ckkn0kerez',
    'c0ckkn0kering',
    'c0ckkn0kerrs',
    'c0ckkn0kerrz',
    'c0ckkn0kers',
    'c0ckkn0kerz',
    'c0ckm0nglerers',
    'c0ckm0nglererz',
    'c0ckm0ngleres',
    'c0ckm0nglerez',
    'c0ckm0nglering',
    'c0ckm0nglerrs',
    'c0ckm0nglerrz',
    'c0ckm0nglers',
    'c0ckm0nglerz',
    'c0ckm0ngruelers',
    'c0ckm0ngruelerz',
    'c0ckm0ngrueles',
    'c0ckm0ngruelez',
    'c0ckm0ngrueling',
    'c0ckm0ngruelrs',
    'c0ckm0ngruelrz',
    'c0ckm0ngruels',
    'c0ckm0ngruelz',
    'c0ckm0nkeyers',
    'c0ckm0nkeyerz',
    'c0ckm0nkeyes',
    'c0ckm0nkeyez',
    'c0ckm0nkeying',
    'c0ckm0nkeyrs',
    'c0ckm0nkeyrz',
    'c0ckm0nkeys',
    'c0ckm0nkeyz',
    'c0ckmasterers',
    'c0ckmastererz',
    'c0ckmasteres',
    'c0ckmasterez',
    'c0ckmastering',
    'c0ckmasterrs',
    'c0ckmasterrz',
    'c0ckmasters',
    'c0ckmasterz',
    'c0ckmuncherers',
    'c0ckmunchererz',
    'c0ckmuncheres',
    'c0ckmuncherez',
    'c0ckmunchering',
    'c0ckmuncherrs',
    'c0ckmuncherrz',
    'c0ckmunchers',
    'c0ckmuncherz',
    'c0ckmunches',
    'c0ckmunchez',
    'c0ckmunching',
    'c0ckmunchrs',
    'c0ckmunchrz',
    'c0ckmunchs',
    'c0ckmunchz',
    'c0ckn0seers',
    'c0ckn0seerz',
    'c0ckn0sees',
    'c0ckn0seez',
    'c0ckn0seing',
    'c0ckn0sers',
    'c0ckn0serz',
    'c0ckn0ses',
    'c0ckn0sez',
    'c0cknuggeters',
    'c0cknuggeterz',
    'c0cknuggetes',
    'c0cknuggetez',
    'c0cknuggeting',
    'c0cknuggetrs',
    'c0cknuggetrz',
    'c0cknuggets',
    'c0cknuggetz',
    'c0cksers',
    'c0ckserz',
    'c0ckses',
    'c0cksez',
    'c0ckshiters',
    'c0ckshiterz',
    'c0ckshites',
    'c0ckshitez',
    'c0ckshiting',
    'c0ckshitrs',
    'c0ckshitrz',
    'c0ckshits',
    'c0ckshitz',
    'c0cksing',
    'c0cksm0kerers',
    'c0cksm0kererz',
    'c0cksm0keres',
    'c0cksm0kerez',
    'c0cksm0kering',
    'c0cksm0kerrs',
    'c0cksm0kerrz',
    'c0cksm0kers',
    'c0cksm0kerz',
    'c0cksmithers',
    'c0cksmitherz',
    'c0cksmithes',
    'c0cksmithez',
    'c0cksmithing',
    'c0cksmithrs',
    'c0cksmithrz',
    'c0cksmiths',
    'c0cksmithz',
    'c0cksnifferers',
    'c0cksniffererz',
    'c0cksnifferes',
    'c0cksnifferez',
    'c0cksniffering',
    'c0cksnifferrs',
    'c0cksnifferrz',
    'c0cksniffers',
    'c0cksnifferz',
    'c0cksrs',
    'c0cksrz',
    'c0ckss',
    'c0cksuck ers',
    'c0cksuck erz',
    'c0cksuck es',
    'c0cksuck ez',
    'c0cksuck ing',
    'c0cksuck rs',
    'c0cksuck rz',
    'c0cksuck s',
    'c0cksuck z',
    'c0cksucked ers',
    'c0cksucked erz',
    'c0cksucked es',
    'c0cksucked ez',
    'c0cksucked ing',
    'c0cksucked rs',
    'c0cksucked rz',
    'c0cksucked s',
    'c0cksucked z',
    'c0cksuckerers',
    'c0cksuckererz',
    'c0cksuckeres',
    'c0cksuckerez',
    'c0cksuckering',
    'c0cksuckerrs',
    'c0cksuckerrz',
    'c0cksuckers',
    'c0cksuckerz',
    'c0cksuckingers',
    'c0cksuckingerz',
    'c0cksuckinges',
    'c0cksuckingez',
    'c0cksuckinging',
    'c0cksuckingrs',
    'c0cksuckingrz',
    'c0cksuckings',
    'c0cksuckingz',
    'c0cksucks ers',
    'c0cksucks erz',
    'c0cksucks es',
    'c0cksucks ez',
    'c0cksucks ing',
    'c0cksucks rs',
    'c0cksucks rz',
    'c0cksucks s',
    'c0cksucks z',
    'c0cksukaers',
    'c0cksukaerz',
    'c0cksukaes',
    'c0cksukaez',
    'c0cksukaing',
    'c0cksukars',
    'c0cksukarz',
    'c0cksukas',
    'c0cksukaz',
    'c0cksukkaers',
    'c0cksukkaerz',
    'c0cksukkaes',
    'c0cksukkaez',
    'c0cksukkaing',
    'c0cksukkars',
    'c0cksukkarz',
    'c0cksukkas',
    'c0cksukkaz',
    'c0cksz',
    'c0ckwaffleers',
    'c0ckwaffleerz',
    'c0ckwafflees',
    'c0ckwaffleez',
    'c0ckwaffleing',
    'c0ckwafflers',
    'c0ckwafflerz',
    'c0ckwaffles',
    'c0ckwafflez',
    'c0kers',
    'c0kerz',
    'c0kes',
    'c0kez',
    'c0king',
    'c0kmuncherers',
    'c0kmunchererz',
    'c0kmuncheres',
    'c0kmuncherez',
    'c0kmunchering',
    'c0kmuncherrs',
    'c0kmuncherrz',
    'c0kmunchers',
    'c0kmuncherz',
    'c0krs',
    'c0krz',
    'c0ksuckaers',
    'c0ksuckaerz',
    'c0ksuckaes',
    'c0ksuckaez',
    'c0ksuckaing',
    'c0ksuckars',
    'c0ksuckarz',
    'c0ksuckas',
    'c0ksuckaz',
    'ℂ0ℳ',
    'c0ℳ',
    'camel jockey',
    'camel-jockeys',
    'cameljockeys',
    'cameltoe',
    'camgirl',
    'camslut',
    'camwhore',
    'cappie',
    'carpet muncherers',
    'carpet munchererz',
    'carpet muncheres',
    'carpet muncherez',
    'carpet munchering',
    'carpet muncherrs',
    'carpet muncherrz',
    'carpet munchers',
    'carpet muncherz',
    'carpetmuncherers',
    'carpetmunchererz',
    'carpetmuncheres',
    'carpetmuncherez',
    'carpetmunchering',
    'carpetmuncherrs',
    'carpetmuncherrz',
    'carpetmunchers',
    'carpetmuncherz',
    'carruth',
    'cawk',
    'cherry popper',
    'cherrypopper',
    'chesticle',
    'chick slick',
    'chickslick',
    'chincers',
    'chincerz',
    'chinces',
    'chincez',
    'chincing',
    'chincrs',
    'chincrz',
    'chincss',
    'chincz',
    'ching chong',
    'chingas',
    'chingaz',
    'chinkers',
    'chinkerz',
    'chinkes',
    'chinkez',
    'chinking',
    'chinkrs',
    'chinkrz',
    'chinkz',
    'choad',
    'chocolate rosebuds',
    'chode',
    'chud',
    'cipa',
    'circle jerk',
    'circlejerk',
    'cl1t',
    'clam digger',
    'clam diver',
    'clamdigger',
    'clamdiver',
    'cleveland steamer',
    'click here',
    'clitface',
    'clitfuck',
    'clits',
    'clover clamps',
    'cluster fucks',
    'clusterfuckers',
    'clusterfuckerz',
    'clusterfuckes',
    'clusterfuckez',
    'clusterfucking',
    'clusterfuckrs',
    'clusterfuckrz',
    'clusterfucks',
    'clusterfuckz',
    'cnuters',
    'cnuterz',
    'cnutes',
    'cnutez',
    'cnuting',
    'cnutrs',
    'cnutrz',
    'cnuts',
    'cnutz',
    'cock blocker',
    'cock cowboy',
    'cock fight',
    'cock knob',
    'cock licker',
    'cock lover',
    'cock nob',
    'cock queen',
    'cock rider',
    'cock smith',
    'cock sucker',
    'cock tail',
    'cock tease',
    'cockass',
    'cockbite',
    'cockblocker',
    'cockburger',
    'cockcowboy',
    'cockface',
    'cockfight',
    'cockfucker',
    'cockhead',
    'cockjockey',
    'cockknob',
    'cockknoker',
    'cocklicker',
    'cocklover',
    'cockmaster',
    'cockmongler',
    'cockmongruel',
    'cockmonkey',
    'cockmuncher',
    'cocknob',
    'cocknose',
    'cocknugget',
    'cockqueen',
    'cockrider',
    'cocks man',
    'cockshit',
    'cocksman',
    'cocksmith',
    'cocksmoker',
    'cocksniffer',
    'cocksucer',
    'cocksucked',
    'cocksucker',
    'cocksucking',
    'cocksucks',
    'cocksuka',
    'cocksukka',
    'cocktail',
    'cocktease',
    'cockwaffle',
    'cokmuncher',
    'coksucka',
    'ℂℴℳ',
    'ℂoℳ',
    'ℂom',
    'cℴℳ',
    'ℂℴm',
    'commie fornia',
    'commiefornia',
    'coochies',
    'coochys',
    'coonss',
    'cooters',
    'coprolagnia',
    'coprophilia',
    'copulate',
    'corn hole',
    'cornhole',
    'crack pipe',
    'crack whore',
    'crackpipe',
    'crackwhore',
    'crappersuck',
    'crappy',
    'craquer',
    'creampie',
    'crotch jockey',
    'crotch monkey',
    'crotch rot',
    'crotchjockey',
    'crotchmonkey',
    'crotchrot',
    'cuckservative',
    'cum bubbles',
    'cum dumpsters',
    'cum fest',
    'cum guzzlers',
    'cum jockeys',
    'cum quat',
    'cum queen',
    'cum shots',
    'cum sluts',
    'cum tarts',
    'cumbubbleers',
    'cumbubbleerz',
    'cumbubblees',
    'cumbubbleez',
    'cumbubbleing',
    'cumbubblers',
    'cumbubblerz',
    'cumbubbles',
    'cumbubblez',
    'cumdumpsterers',
    'cumdumpstererz',
    'cumdumpsteres',
    'cumdumpsterez',
    'cumdumpstering',
    'cumdumpsterrs',
    'cumdumpsterrz',
    'cumdumpsters',
    'cumdumpsterz',
    'cumers',
    'cumerz',
    'cumes',
    'cumez',
    'cumfest',
    'cumguzzlerers',
    'cumguzzlererz',
    'cumguzzleres',
    'cumguzzlerez',
    'cumguzzlering',
    'cumguzzlerrs',
    'cumguzzlerrz',
    'cumguzzlers',
    'cumguzzlerz',
    'cuming',
    'cumj0ckeyers',
    'cumj0ckeyerz',
    'cumj0ckeyes',
    'cumj0ckeyez',
    'cumj0ckeying',
    'cumj0ckeyrs',
    'cumj0ckeyrz',
    'cumj0ckeys',
    'cumj0ckeyz',
    'cumjockeys',
    'cummerers',
    'cummererz',
    'cummeres',
    'cummerez',
    'cummering',
    'cummerrs',
    'cummerrz',
    'cummers',
    'cummerz',
    'cummingers',
    'cummingerz',
    'cumminges',
    'cummingez',
    'cumminging',
    'cummingrs',
    'cummingrz',
    'cummingz',
    'cumqueen',
    'cumrs',
    'cumrz',
    'cumsers',
    'cumserz',
    'cumses',
    'cumsez',
    'cumsh0ters',
    'cumsh0terz',
    'cumsh0tes',
    'cumsh0tez',
    'cumsh0ting',
    'cumsh0trs',
    'cumsh0trz',
    'cumsh0ts',
    'cumsh0tz',
    'cumshotss',
    'cumsing',
    'cumsluters',
    'cumsluterz',
    'cumslutes',
    'cumslutez',
    'cumsluting',
    'cumslutrs',
    'cumslutrz',
    'cumsluts',
    'cumslutz',
    'cumsrs',
    'cumsrz',
    'cumss',
    'cumstains',
    'cumsz',
    'cumtarters',
    'cumtarterz',
    'cumtartes',
    'cumtartez',
    'cumtarting',
    'cumtartrs',
    'cumtartrz',
    'cumtarts',
    'cumtartz',
    'cumz',
    'cunnie',
    'cunnilingus',
    'cunt asss',
    'cunt faces',
    'cunt fucker',
    'cunt holes',
    'cunt lick s',
    'cunt licker s',
    'cunt lickers',
    'cunt licking s',
    'cunt rags',
    'cunt sluts',
    'cuntassers',
    'cuntasserz',
    'cuntasses',
    'cuntassez',
    'cuntassing',
    'cuntassrs',
    'cuntassrz',
    'cuntasss',
    'cuntassz',
    'cuntbag',
    'cuntfaceers',
    'cuntfaceerz',
    'cuntfacees',
    'cuntfaceez',
    'cuntfaceing',
    'cuntfacers',
    'cuntfacerz',
    'cuntfaces',
    'cuntfacez',
    'cuntfucker',
    'cunth0leers',
    'cunth0leerz',
    'cunth0lees',
    'cunth0leez',
    'cunth0leing',
    'cunth0lers',
    'cunth0lerz',
    'cunth0les',
    'cunth0lez',
    'cuntholes',
    'cunthunters',
    'cuntlick ers',
    'cuntlick erz',
    'cuntlick es',
    'cuntlick ez',
    'cuntlick ing',
    'cuntlick rs',
    'cuntlick rz',
    'cuntlick s',
    'cuntlick z',
    'cuntlicker ers',
    'cuntlicker erz',
    'cuntlicker es',
    'cuntlicker ez',
    'cuntlicker ing',
    'cuntlicker rs',
    'cuntlicker rz',
    'cuntlicker s',
    'cuntlicker z',
    'cuntlickerers',
    'cuntlickererz',
    'cuntlickeres',
    'cuntlickerez',
    'cuntlickering',
    'cuntlickerrs',
    'cuntlickerrz',
    'cuntlickers',
    'cuntlickerz',
    'cuntlicking ers',
    'cuntlicking erz',
    'cuntlicking es',
    'cuntlicking ez',
    'cuntlicking ing',
    'cuntlicking rs',
    'cuntlicking rz',
    'cuntlicking s',
    'cuntlicking z',
    'cuntlickings',
    'cuntlicks',
    'cunton',
    'cuntragers',
    'cuntragerz',
    'cuntrages',
    'cuntragez',
    'cuntraging',
    'cuntragrs',
    'cuntragrz',
    'cuntrags',
    'cuntragz',
    'cuntsers',
    'cuntserz',
    'cuntses',
    'cuntsez',
    'cuntsing',
    'cuntsluters',
    'cuntsluterz',
    'cuntslutes',
    'cuntslutez',
    'cuntsluting',
    'cuntslutrs',
    'cuntslutrz',
    'cuntsluts',
    'cuntslutz',
    'cuntsrs',
    'cuntsrz',
    'cuntss',
    'cuntsz',
    'curb job',
    'cyber sex',
    'cyber slimer',
    'cyberfucked',
    'cyberfuckers',
    'cyberfucking',
    'cybersex',
    'cyberslimer',
    'd_bag',
    'd00chbagers',
    'd00chbagerz',
    'd00chbages',
    'd00chbagez',
    'd00chbaging',
    'd00chbagrs',
    'd00chbagrz',
    'd00chbags',
    'd00chbagz',
    'd00kieers',
    'd00kieerz',
    'd00kiees',
    'd00kieez',
    'd00kieing',
    'd00kiers',
    'd00kierz',
    'd00kies',
    'd00kiez',
    'd00shers',
    'd00sherz',
    'd00shes',
    'd00shez',
    'd00shing',
    'd00shrs',
    'd00shrz',
    'd00shs',
    'd00shz',
    'd0g-fuckerers',
    'd0g-fuckererz',
    'd0g-fuckeres',
    'd0g-fuckerez',
    'd0g-fuckering',
    'd0g-fuckerrs',
    'd0g-fuckerrz',
    'd0g-fuckers',
    'd0g-fuckerz',
    'd0gginers',
    'd0gginerz',
    'd0ggines',
    'd0gginez',
    'd0ggingers',
    'd0ggingerz',
    'd0gginges',
    'd0ggingez',
    'd0gginging',
    'd0ggingrs',
    'd0ggingrz',
    'd0ggings',
    'd0ggingz',
    'd0ggining',
    'd0gginrs',
    'd0gginrz',
    'd0ggins',
    'd0gginz',
    'd0ngs',
    'd0nkeyribberers',
    'd0nkeyribbererz',
    'd0nkeyribberes',
    'd0nkeyribberez',
    'd0nkeyribbering',
    'd0nkeyribberrs',
    'd0nkeyribberrz',
    'd0nkeyribbers',
    'd0nkeyribberz',
    'd0uch3s',
    'd0uche-fagers',
    'd0uche-fagerz',
    'd0uche-fages',
    'd0uche-fagez',
    'd0uche-faging',
    'd0uche-fagrs',
    'd0uche-fagrz',
    'd0uche-fags',
    'd0uche-fagz',
    'd0uchebagers',
    'd0uchebagerz',
    'd0uchebages',
    'd0uchebagez',
    'd0uchebaging',
    'd0uchebagrs',
    'd0uchebagrz',
    'd0uchebags',
    'd0uchebagz',
    'd0ucheers',
    'd0ucheerz',
    'd0uchees',
    'd0ucheez',
    'd0ucheing',
    'd0uchers',
    'd0ucherz',
    'd0uches',
    'd0uchewaffleers',
    'd0uchewaffleerz',
    'd0uchewafflees',
    'd0uchewaffleez',
    'd0uchewaffleing',
    'd0uchewafflers',
    'd0uchewafflerz',
    'd0uchewaffles',
    'd0uchewafflez',
    'd0uchez',
    'd1ckers',
    'd1ckerz',
    'd1ckes',
    'd1ckez',
    'd1cking',
    'd1ckrs',
    'd1ckrz',
    'd1cks',
    'd1ckz',
    'd1ld0s',
    'd1ldos',
    'dag0ers',
    'dag0erz',
    'dag0es',
    'dag0ez',
    'dag0ing',
    'dag0rs',
    'dag0rz',
    'dag0s',
    'dag0z',
    'dagoss',
    'dahmer',
    'darkies',
    'date rape',
    'daterape',
    'datnigga',
    'dawgie-style',
    'dbag',
    'de liar',
    'deap throat',
    'deaper',
    'deapthroat',
    'deep throat',
    'deepthroat',
    'defecate',
    'deggo',
    'democrap*',
    'demokkkrat*',
    'demoncrap*',
    'demoncrat*',
    'demonrat*',
    'dendrophilia',
    'deus vult',
    'devilcrat',
    'dick bags',
    'dick beaterss',
    'dick brain',
    'dick faces',
    'dick fart',
    'dick for brains',
    'dick fuckers',
    'dick fucks',
    'dick heads',
    'dick holes',
    'dick juices',
    'dick lick',
    'dick likcer',
    'dick milks',
    'dick mongers',
    'dick slaps',
    'dick suckers',
    'dick suckings',
    'dick wads',
    'dick weasels',
    'dick weeds',
    'dick wods',
    'dick-ishs',
    'dick-sneeze',
    'dickbagers',
    'dickbagerz',
    'dickbages',
    'dickbagez',
    'dickbaging',
    'dickbagrs',
    'dickbagrz',
    'dickbags',
    'dickbagz',
    'dickbeatersers',
    'dickbeaterserz',
    'dickbeaterses',
    'dickbeatersez',
    'dickbeatersing',
    'dickbeatersrs',
    'dickbeatersrz',
    'dickbeaterss',
    'dickbeatersz',
    'dickbrain',
    'dickdippers',
    'dickerz',
    'dickes',
    'dickez',
    'dickfaceers',
    'dickfaceerz',
    'dickfacees',
    'dickfaceez',
    'dickfaceing',
    'dickfacers',
    'dickfacerz',
    'dickfaces',
    'dickfacez',
    'dickflippers',
    'dickforbrains',
    'dickfuckerers',
    'dickfuckererz',
    'dickfuckeres',
    'dickfuckerez',
    'dickfuckering',
    'dickfuckerrs',
    'dickfuckerrz',
    'dickfuckers',
    'dickfuckerz',
    'dickfuckes',
    'dickfuckez',
    'dickfucking',
    'dickfuckrs',
    'dickfuckrz',
    'dickfucks',
    'dickfuckz',
    'dickh0leers',
    'dickh0leerz',
    'dickh0lees',
    'dickh0leez',
    'dickh0leing',
    'dickh0lers',
    'dickh0lerz',
    'dickh0les',
    'dickh0lez',
    'dickheaders',
    'dickheaderz',
    'dickheades',
    'dickheadez',
    'dickheading',
    'dickheadrs',
    'dickheadrz',
    'dickheadss',
    'dickheadz',
    'dickholes',
    'dicking',
    'dickishs',
    'dickjuiceers',
    'dickjuiceerz',
    'dickjuicees',
    'dickjuiceez',
    'dickjuiceing',
    'dickjuicers',
    'dickjuicerz',
    'dickjuices',
    'dickjuicez',
    'dickless',
    'dicklicker',
    'dickm0ngerers',
    'dickm0ngererz',
    'dickm0ngeres',
    'dickm0ngerez',
    'dickm0ngering',
    'dickm0ngerrs',
    'dickm0ngerrz',
    'dickm0ngers',
    'dickm0ngerz',
    'dickman',
    'dickmilkers',
    'dickmilkerz',
    'dickmilkes',
    'dickmilkez',
    'dickmilking',
    'dickmilkrs',
    'dickmilkrz',
    'dickmilks',
    'dickmilkz',
    'dickmongers',
    'dickrippers',
    'dickrs',
    'dickrz',
    'dicksers',
    'dickserz',
    'dickses',
    'dicksez',
    'dicksing',
    'dicksippers',
    'dickslapers',
    'dickslaperz',
    'dickslapes',
    'dickslapez',
    'dickslaping',
    'dickslaprs',
    'dickslaprz',
    'dickslaps',
    'dickslapz',
    'dicksrs',
    'dicksrz',
    'dickss',
    'dicksuckerers',
    'dicksuckererz',
    'dicksuckeres',
    'dicksuckerez',
    'dicksuckering',
    'dicksuckerrs',
    'dicksuckerrz',
    'dicksuckers',
    'dicksuckerz',
    'dicksuckingers',
    'dicksuckingerz',
    'dicksuckinges',
    'dicksuckingez',
    'dicksuckinging',
    'dicksuckingrs',
    'dicksuckingrz',
    'dicksuckings',
    'dicksuckingz',
    'dicksz',
    'dicktickler',
    'dickw0ders',
    'dickw0derz',
    'dickw0des',
    'dickw0dez',
    'dickw0ding',
    'dickw0drs',
    'dickw0drz',
    'dickw0ds',
    'dickw0dz',
    'dickwaders',
    'dickwaderz',
    'dickwades',
    'dickwadez',
    'dickwading',
    'dickwadrs',
    'dickwadrz',
    'dickwads',
    'dickwadz',
    'dickweaselers',
    'dickweaselerz',
    'dickweaseles',
    'dickweaselez',
    'dickweaseling',
    'dickweaselrs',
    'dickweaselrz',
    'dickweasels',
    'dickweaselz',
    'dickweeders',
    'dickweederz',
    'dickweedes',
    'dickweedez',
    'dickweeding',
    'dickweedrs',
    'dickweedrz',
    'dickweeds',
    'dickweedz',
    'dickwhippers',
    'dickwipe',
    'dickwods',
    'dickzipper',
    'dikheads',
    'dildo',
    'dindus',
    'dingleberries',
    'dingleberry',
    'dip shits',
    'dip stick',
    'dipschiits',
    'dipshiters',
    'dipshiterz',
    'dipshites',
    'dipshitez',
    'dipshiting',
    'dipshitrs',
    'dipshitrz',
    'dipshits',
    'dipshitz',
    'dipstick',
    'dirsa',
    'dirty ho',
    'dirty pillows',
    'dirty sanchez',
    'dirtysanchez',
    'dixie dike',
    'dixie dyke',
    'dixiedike',
    'dixiedyke',
    'dlck',
    'dog fuckers',
    'dog style',
    'dogfuckers',
    'doggie style',
    'doggiestyle',
    'doggy stlye',
    'doggystyle',
    'dolcett',
    'dommes',
    'donkey punch',
    'donkey ribbers',
    'donkeyribbers',
    'dooch bags',
    'doochbags',
    'dookie',
    'dooshs',
    'dot heads',
    'dotheads',
    'double dong',
    'double penetration',
    'douch3s',
    'douche bags',
    'douche fags',
    'douche waffles',
    'douchebagss',
    'douchefags',
    'douchewaffles',
    'doucheys',
    'dp action',
    'dragqween',
    'drip dick',
    'dripdick',
    'dry hump',
    'ducheers',
    'ducheerz',
    'duchees',
    'ducheez',
    'ducheing',
    'duchers',
    'ducherz',
    'duches',
    'duchez',
    'dum shits',
    'dumassers',
    'dumasserz',
    'dumasses',
    'dumassez',
    'dumassing',
    'dumassrs',
    'dumassrz',
    'dumasss',
    'dumassz',
    'dumb assers',
    'dumb asserz',
    'dumb asses',
    'dumb assez',
    'dumb assing',
    'dumb assrs',
    'dumb assrz',
    'dumb asss',
    'dumb assz',
    'dumb bitch',
    'dumb fucks',
    'dumb shits',
    'dumbassers',
    'dumbasserz',
    'dumbassess',
    'dumbassez',
    'dumbassing',
    'dumbassrs',
    'dumbassrz',
    'dumbasss',
    'dumbassz',
    'dumbbitch',
    'dumbfuckers',
    'dumbfuckerz',
    'dumbfuckes',
    'dumbfuckez',
    'dumbfucking',
    'dumbfuckrs',
    'dumbfuckrz',
    'dumbfucks',
    'dumbfuckz',
    'dumbocrats',
    'dummys',
    'dumocrats',
    'dumshiters',
    'dumshiterz',
    'dumshites',
    'dumshitez',
    'dumshiting',
    'dumshitrs',
    'dumshitrz',
    'dumshits',
    'dumshitz',
    'dvda',
    'dykeers',
    'dykeerz',
    'dykees',
    'dykeez',
    'dykeing',
    'dykers',
    'dykerz',
    'dykess',
    'dykez',
    'easy slut',
    'easyslut',
    'eat me',
    'eat my ass',
    'eat pussy',
    'eatballs',
    'eatme',
    'eatpussy',
    'ecchi',
    'effing',
    'ejaculate',
    'ejaculatings',
    'ejaculation',
    'ejakulate',
    'erection',
    'erotism',
    'eunuch',
    'evl',
    'excrement',
    'f a g',
    'f toyota',
    'f u c k e rers',
    'f u c k e rerz',
    'f u c k e res',
    'f u c k e rez',
    'f u c k e ring',
    'f u c k e rrs',
    'f u c k e rrz',
    'f u c k e rs',
    'f u c k e rz',
    'f u c kers',
    'f u c kerz',
    'f u c kes',
    'f u c kez',
    'f u c king',
    'f u c krs',
    'f u c krz',
    'f u c ks',
    'f u c kz',
    'f--ing',
    'f.i.n.e.',
    "f'ing",
    'f@cker',
    'f@gg0t',
    'f@ggot',
    'f@gs',
    'f***in',
    'f*cking',
    'f*gg○t',
    'f00ker',
    'f00kes',
    'f00kez',
    'f00king',
    'f00krs',
    'f00krz',
    'f00ks',
    'f00kz',
    'f465',
    'f4gg0t',
    'f4nny',
    'f8ck',
    'face fucker',
    'facefucker',
    'faig',
    'fanny bandit',
    'fanny flaps',
    'fanny fuckers',
    'fannybandits',
    'fannyers',
    'fannyerz',
    'fannyes',
    'fannyez',
    'fannyflaps',
    'fannyfucker',
    'fanyy',
    'faqqot',
    'fartkn0cker',
    'fartknockers',
    'fast fuck',
    'fastfuck',
    'fat ass',
    'fat fucker',
    'fat@ss',
    'fatass',
    'fatfucker',
    'fcuked',
    'fcuker',
    'fcuking',
    'fecal',
    'felching',
    'fellate',
    'fellatio',
    'feltch',
    'female squirting',
    'femdom',
    'fgrn',
    'figging',
    'finger food',
    'finger fucker',
    'fingerbang',
    'fingerfood',
    'fingerfuck',
    'fingering',
    'fist fucker',
    'fistfuck',
    'fisting',
    'flasher',
    'flatulence',
    'floggin the dolphin',
    'fondle',
    'fooker',
    'foot fetish',
    'foot fucker',
    'foot licker',
    'footaction',
    'footfucker',
    'footjob',
    'footlicker',
    'footstar',
    'fore skin',
    'foreskin',
    'fornicate',
    'four 20',
    'four twenty',
    'fourtwenty',
    'freak fuck',
    'freakfuck',
    'freaky fucker',
    'freakyfucker',
    'free 4 all',
    'free fuck',
    'freeforall',
    'freefuck',
    'frigginfuck',
    'frotting',
    'fubars',
    'fuck ass',
    'fuck bags',
    'fuck boys',
    'fuck brains',
    'fuck buddy',
    'fuck buttons',
    'fuck butts',
    'fuck faces',
    'fuck fest',
    'fuck freak',
    'fuck friend',
    'fuck headss',
    'fuck her',
    'fuck holes',
    'fuck it',
    'fuck knob',
    'fuck me',
    'fuck monkey',
    'fuck nuts',
    'fuck nutt',
    'fuck off',
    'fuck pig',
    'fuck stick',
    'fuck tard',
    'fuck tart',
    'fuck them',
    'fuck up',
    'fuck wads',
    'fuck whits',
    'fuck whore',
    'fuck wit',
    'fuck you',
    'fuck-offs',
    "fuck's",
    'fuck0ff',
    'fucka$$s',
    'fuckb0yers',
    'fuckb0yerz',
    'fuckb0yes',
    'fuckb0yez',
    'fuckb0ying',
    'fuckb0yrs',
    'fuckb0yrz',
    'fuckb0ys',
    'fuckb0yz',
    'fuckbag',
    'fuckboys',
    'fuckbrain',
    'fuckbuddy',
    'fuckbutter',
    'fuckbuttes',
    'fuckbuttez',
    'fuckbutting',
    'fuckbuttr',
    'fuckbutts',
    'fuckbuttz',
    'fucken',
    'fucker suckers',
    'fuckface',
    'fuckfest',
    'fuckfreak',
    'fuckfriend',
    'fuckh0le',
    'fuckhead',
    'fuckher',
    'fuckholes',
    'fuckit',
    'fuckknob',
    'fuckme',
    'fuckmonkey',
    'fucknuggets',
    'fucknut',
    'fuckoff',
    'fuckpig',
    'fuckstains',
    'fuckstick',
    'fucktard',
    'fucktart',
    'fuckup',
    'fuckwaders',
    'fuckwaderz',
    'fuckwades',
    'fuckwadez',
    'fuckwading',
    'fuckwadrs',
    'fuckwadrz',
    'fuckwads',
    'fuckwadz',
    'fuckwhiters',
    'fuckwhiterz',
    'fuckwhites',
    'fuckwhitez',
    'fuckwhiting',
    'fuckwhitrs',
    'fuckwhitrz',
    'fuckwhits',
    'fuckwhitz',
    'fuckwhore',
    'fuckwiters',
    'fuckwiterz',
    'fuckwites',
    'fuckwitez',
    'fuckwiting',
    'fuckwitrs',
    'fuckwitrz',
    'fuckwits',
    'fuckwitters',
    'fuckwitterz',
    'fuckwittes',
    'fuckwittez',
    'fuckwitting',
    'fuckwittrs',
    'fuckwittrz',
    'fuckwitts',
    'fuckwittz',
    'fuckwitz',
    'fuckyou',
    'fudge packerers',
    'fudge packererz',
    'fudge packeres',
    'fudge packerez',
    'fudge packering',
    'fudge packerrs',
    'fudge packerrz',
    'fudge packers',
    'fudge packerz',
    'fudge pakcers',
    'fudgepackerers',
    'fudgepackererz',
    'fudgepackeres',
    'fudgepackerez',
    'fudgepackering',
    'fudgepackerrs',
    'fudgepackerrz',
    'fudgepackers',
    'fudgepackerz',
    'fuhrer',
    'fuk whits',
    'fuk wits',
    'fukerers',
    'fukererz',
    'fukeres',
    'fukerez',
    'fukering',
    'fukerrs',
    'fukerrz',
    'fukers',
    'fukerz',
    'fukes',
    'fukez',
    'fuking',
    'fukkerers',
    'fukkererz',
    'fukkeres',
    'fukkerez',
    'fukkering',
    'fukkerrs',
    'fukkerrz',
    'fukkers',
    'fukkerz',
    'fukkiners',
    'fukkinerz',
    'fukkines',
    'fukkinez',
    'fukkining',
    'fukkinrs',
    'fukkinrz',
    'fukkins',
    'fukkinz',
    'fukrs',
    'fukrz',
    'fuksers',
    'fukserz',
    'fukses',
    'fuksez',
    'fuksing',
    'fuksrs',
    'fuksrz',
    'fukss',
    'fuksz',
    'fukwhiters',
    'fukwhiterz',
    'fukwhites',
    'fukwhitez',
    'fukwhiting',
    'fukwhitrs',
    'fukwhitrz',
    'fukwhits',
    'fukwhitz',
    'fukwiters',
    'fukwiterz',
    'fukwites',
    'fukwitez',
    'fukwiting',
    'fukwitrs',
    'fukwitrz',
    'fukwits',
    'fukwitz',
    'fukz',
    'fun fuck',
    'funfuck',
    'fuqq',
    'futanari',
    'fuuck',
    'fux0rers',
    'fux0rerz',
    'fux0res',
    'fux0rez',
    'fux0ring',
    'fux0rrs',
    'fux0rrz',
    'fux0rs',
    'fux0rz',
    'fuxers',
    'fuxerz',
    'fuxes',
    'fuxez',
    'fuxing',
    'fuxrs',
    'fuxrz',
    'fuxs',
    'fuxz',
    'fvcked',
    'fvcking',
    'fvcks',
    'fxcks',
    'g unit',
    'g-spot',
    'g00chers',
    'g00cherz',
    'g00ches',
    'g00chez',
    'g00ching',
    'g00chrs',
    'g00chrz',
    'g00chs',
    'g00chz',
    'g00kers',
    'g00kerz',
    'g00kes',
    'g00kez',
    'g00king',
    'g00krs',
    'g00krz',
    'g00ks',
    'g00kz',
    'g0atseers',
    'g0atseerz',
    'g0atsees',
    'g0atseez',
    'g0atseing',
    'g0atsers',
    'g0atserz',
    'g0atses',
    'g0atsez',
    'g0d damn',
    'g0d-damers',
    'g0d-damerz',
    'g0d-dames',
    'g0d-damez',
    'g0d-daming',
    'g0d-damneders',
    'g0d-damnederz',
    'g0d-damnedes',
    'g0d-damnedez',
    'g0d-damneding',
    'g0d-damnedrs',
    'g0d-damnedrz',
    'g0d-damneds',
    'g0d-damnedz',
    'g0d-damrs',
    'g0d-damrz',
    'g0d-dams',
    'g0d-damz',
    'g0damnit',
    'g0ddammit',
    'g0ddamneders',
    'g0ddamnederz',
    'g0ddamnedes',
    'g0ddamnedez',
    'g0ddamneding',
    'g0ddamnedrs',
    'g0ddamnedrz',
    'g0ddamneds',
    'g0ddamnedz',
    'g0ddamners',
    'g0ddamnerz',
    'g0ddamnes',
    'g0ddamnez',
    'g0ddamning',
    'g0ddamniters',
    'g0ddamniterz',
    'g0ddamnites',
    'g0ddamnitez',
    'g0ddamniting',
    'g0ddamnitrs',
    'g0ddamnitrz',
    'g0ddamnits',
    'g0ddamnitz',
    'g0ddamnrs',
    'g0ddamnrz',
    'g0ddamns',
    'g0ddamnz',
    'gang banger',
    'gangbanged',
    'gangbanger',
    'gangbangs',
    'gay asss',
    'gay bobs',
    'gay fuckists',
    'gay fucks',
    'gay lords',
    'gay mutha fuckin queer',
    'gay sexs',
    'gay tards',
    'gay wads',
    'gayassers',
    'gayasserz',
    'gayasses',
    'gayassez',
    'gayassing',
    'gayassrs',
    'gayassrz',
    'gayasss',
    'gayassz',
    'gayb0bers',
    'gayb0berz',
    'gayb0bes',
    'gayb0bez',
    'gayb0bing',
    'gayb0brs',
    'gayb0brz',
    'gayb0bs',
    'gayb0bz',
    'gaybobs',
    'gayboy',
    'gayd0ers',
    'gayd0erz',
    'gayd0es',
    'gayd0ez',
    'gayd0ing',
    'gayd0rs',
    'gayd0rz',
    'gayd0s',
    'gayd0z',
    'gaydos',
    'gayfuckers',
    'gayfuckerz',
    'gayfuckes',
    'gayfuckez',
    'gayfucking',
    'gayfuckisters',
    'gayfuckisterz',
    'gayfuckistes',
    'gayfuckistez',
    'gayfuckisting',
    'gayfuckistrs',
    'gayfuckistrz',
    'gayfuckists',
    'gayfuckistz',
    'gayfuckrs',
    'gayfuckrz',
    'gayfucks',
    'gayfuckz',
    'gayl0rders',
    'gayl0rderz',
    'gayl0rdes',
    'gayl0rdez',
    'gayl0rding',
    'gayl0rdrs',
    'gayl0rdrz',
    'gayl0rds',
    'gayl0rdz',
    'gaylords',
    'gaymuthafuckinwhore',
    'gaysexers',
    'gaysexerz',
    'gaysexes',
    'gaysexez',
    'gaysexing',
    'gaysexrs',
    'gaysexrz',
    'gaysexs',
    'gaysexz',
    'gayss',
    'gaytarders',
    'gaytarderz',
    'gaytardes',
    'gaytardez',
    'gaytarding',
    'gaytardrs',
    'gaytardrz',
    'gaytards',
    'gaytardz',
    'gaywaders',
    'gaywaderz',
    'gaywades',
    'gaywadez',
    'gaywading',
    'gaywadrs',
    'gaywadrz',
    'gaywads',
    'gaywadz',
    'genitals',
    'get it on',
    'getiton',
    'geys',
    'gfys',
    'ghays',
    'gheys',
    'giant cock',
    'giehn',
    'girl on top',
    'girls gone wild',
    'give head',
    'givehead',
    'glazeddonut',
    'glib-erals',
    'gliberals',
    'goatcx',
    'goatse',
    'god damed mutha fucka',
    'god damit',
    'god damned',
    'god manit',
    'god-dam',
    'goddamit',
    'goddamned',
    'goddamnes',
    'goddamnmuthafucker',
    'gokkun',
    'golden shower',
    'gonorrehea',
    'gonzagas',
    'goo girl',
    'goochs',
    'goodpoop',
    'gookss',
    'gookz',
    'goregasm',
    'got jesus',
    'got2haveit',
    'gotohell',
    'goyper',
    'grope',
    'group sex',
    'gtfo',
    'guro',
    'h0areers',
    'h0areerz',
    'h0arees',
    'h0areez',
    'h0areing',
    'h0bag',
    'h0eers',
    'h0eerz',
    'h0ees',
    'h0eez',
    'h0eing',
    'h0erers',
    'h0ererz',
    'h0eres',
    'h0erez',
    'h0ering',
    'h0errs',
    'h0errz',
    'h0ers',
    'h0erz',
    'h0es',
    'h0ez',
    'h0m0dumbshiters',
    'h0m0dumbshiterz',
    'h0m0dumbshites',
    'h0m0dumbshitez',
    'h0m0dumbshiting',
    'h0m0dumbshitrs',
    'h0m0dumbshitrz',
    'h0m0dumbshits',
    'h0m0dumbshitz',
    'h0m0ers',
    'h0m0erz',
    'h0m0es',
    'h0m0ez',
    'h0m0ing',
    'h0m0rs',
    'h0m0rz',
    'h0m0s',
    'h0m0z',
    'h0mos',
    'h0nkeyers',
    'h0nkeyerz',
    'h0nkeyes',
    'h0nkeyez',
    'h0nkeying',
    'h0nkeyrs',
    'h0nkeyrz',
    'h0nkeys',
    'h0nkeyz',
    'h0rniesters',
    'h0rniesterz',
    'h0rniestes',
    'h0rniestez',
    'h0rniesting',
    'h0rniestrs',
    'h0rniestrz',
    'h0rniests',
    'h0rniestz',
    'h0rnyers',
    'h0rnyerz',
    'h0rnyes',
    'h0rnyez',
    'h0rnying',
    'h0rnyrs',
    'h0rnyrz',
    'h0rnys',
    'h0rnyz',
    'h0rseshit',
    'hairy axe wound',
    'hammerskins',
    'hand jobs',
    'handj0bers',
    'handj0berz',
    'handj0bes',
    'handj0bez',
    'handj0bing',
    'handj0brs',
    'handj0brz',
    'handj0bs',
    'handj0bz',
    'handjobs',
    'hardcoresex',
    'hardon',
    'harem',
    'hchillary',
    'he hate me',
    'head fuck',
    'headfuck',
    'hehateme',
    'hellno',
    'hellyes',
    'hen house',
    'henhouse',
    'hentai',
    'herpes',
    'hershey hi way',
    'hersheyhighway',
    'hersheyhiway',
    'hershy high way',
    'hesheers',
    'hesheerz',
    'heshees',
    'hesheez',
    'hesheing',
    'heshers',
    'hesherz',
    'heshes',
    'heshez',
    'hffh',
    'hiel hitler',
    'hildabeast',
    'hildebeast',
    'hindquarters',
    'hitlery',
    'hivs',
    'ho mo',
    'hoares',
    'hobags',
    'hole stuffer',
    'holestuffer',
    'hom0s',
    'homey sock',
    'homo bangers',
    'homo dumbshits',
    'homo sexual',
    'homobangers',
    'homodumbshits',
    'homoerotic',
    'homoeys',
    'homosexual',
    'honkers',
    'honkeys',
    'honkys',
    'hood_rats',
    'hoodrats',
    'hookers',
    'hooters',
    'horney',
    'horniest',
    'horny',
    'horse sh1t',
    'horse shit',
    'horsesh1t',
    'horseshitterry',
    'horseshittery',
    'hose job',
    'hosejob',
    'hoser',
    'hot carl',
    'hot chick',
    'hot damn',
    'hot pussy',
    'hot to trot',
    'hot2trot',
    'hotdamn',
    'hotpussy',
    'hotsex',
    'hottotrot',
    'how to kill',
    'hshillary',
    'huge fat',
    'humping',
    'hussein obama',
    'hussy',
    'hustler',
    'i l l e a g l e s',
    'id ten t',
    'id10t',
    'idoit',
    'ill beagles',
    'ill eagles',
    'illeagle',
    'illegals',
    'imam obama',
    'in the ass',
    'in the buff',
    'incest',
    'injuns',
    'insest',
    'inter course',
    'inter racial',
    'intercourse',
    'interracial',
    'intheass',
    'inthebuff',
    'j3rk0ffs',
    'jack asss',
    'jack off',
    'jack the ripper',
    'jack-0ff ers',
    'jack-0ff erz',
    'jack-0ff es',
    'jack-0ff ez',
    'jack-0ff ing',
    'jack-0ff rs',
    'jack-0ff rz',
    'jack-0ff s',
    'jack-0ff z',
    'jack-off s',
    'jack0ffers',
    'jack0fferz',
    'jack0ffes',
    'jack0ffez',
    'jack0ffing',
    'jack0ffrs',
    'jack0ffrz',
    'jack0ffs',
    'jack0ffz',
    'jackassers',
    'jackasserz',
    'jackassez',
    'jackassing',
    'jackassrs',
    'jackassrz',
    'jackasss',
    'jackassz',
    'jackh0le',
    'jackholes',
    'jackie coakley',
    'jacking off',
    'jackoffs',
    'jacktheripper',
    'jagoff',
    'jail bait',
    'jailbait',
    'jap crap',
    'japcrap',
    'japers',
    'japerz',
    'japez',
    'japin',
    'japrs',
    'japrz',
    'japss',
    'japz',
    'jelly donut',
    'jerk off',
    'jerk-0ff ers',
    'jerk-0ff erz',
    'jerk-0ff es',
    'jerk-0ff ez',
    'jerk-0ff ing',
    'jerk-0ff rs',
    'jerk-0ff rz',
    'jerk-0ff s',
    'jerk-0ff z',
    'jerk-off s',
    'jerk-offs',
    'jerk0ffers',
    'jerk0fferz',
    'jerk0ffes',
    'jerk0ffez',
    'jerk0ffing',
    'jerk0ffrs',
    'jerk0ffrz',
    'jerk0ffs',
    'jerk0ffz',
    'jerkass',
    'jerkeds',
    'jerkoffs',
    'jewbag',
    'jigaboo',
    'jiggaboo',
    'jiggas',
    'jiggaz',
    'jiggerboo',
    'jismers',
    'jismerz',
    'jismes',
    'jismez',
    'jisming',
    'jismrs',
    'jismrz',
    'jisms',
    'jismz',
    'jiz ers',
    'jiz erz',
    'jiz es',
    'jiz ez',
    'jiz ing',
    'jiz juice',
    'jiz rs',
    'jiz rz',
    'jiz s',
    'jiz z',
    'jizim',
    'jizjuice',
    'jizm ers',
    'jizm erz',
    'jizm es',
    'jizm ez',
    'jizm ing',
    'jizm rs',
    'jizm rz',
    'jizm s',
    'jizm z',
    'jizms',
    'jizs',
    'jizz bags',
    'jizzeds',
    'jizzers',
    'jizzerz',
    'jizzes',
    'jizzez',
    'jizzim',
    'jizzing',
    'jizzrs',
    'jizzrz',
    'jizzs',
    'jizzz',
    'joos',
    'juggalo',
    'juggs',
    'jungle bunnies',
    'jungle bunny',
    'k00chers',
    'k00cherz',
    'k00ches',
    'k00chez',
    'k00ching',
    'k00chrs',
    'k00chrz',
    'k00chs',
    'k00chz',
    'k00tchers',
    'k00tcherz',
    'k00tches',
    'k00tchez',
    'k00tching',
    'k00tchrs',
    'k00tchrz',
    'k00tchs',
    'k00tchz',
    'k0ckers',
    'k0ckerz',
    'k0ckes',
    'k0ckez',
    'k0cking',
    'k0ckrs',
    'k0ckrz',
    'k0cks',
    'k0ckz',
    'k0ndumers',
    'k0ndumerz',
    'k0ndumes',
    'k0ndumez',
    'k0nduming',
    'k0ndumrs',
    'k0ndumrz',
    'k0ndumsers',
    'k0ndumserz',
    'k0ndumses',
    'k0ndumsez',
    'k0ndumsing',
    'k0ndumsrs',
    'k0ndumsrz',
    'k0ndumss',
    'k0ndumsz',
    'k0ndumz',
    'kabark',
    'kawkers',
    'kawkerz',
    'kawkes',
    'kawkez',
    'kawking',
    'kawkrs',
    'kawkrz',
    'kawks',
    'kawkz',
    'kcuf',
    'kigy',
    'kikess',
    'killary',
    'kinbaku',
    'kinkster',
    'kinkys',
    'kiss ass',
    'kissass',
    'klasp',
    'kn0b end',
    'kn0beaders',
    'kn0beaderz',
    'kn0beades',
    'kn0beadez',
    'kn0beading',
    'kn0beadrs',
    'kn0beadrz',
    'kn0beads',
    'kn0beadz',
    'kn0beders',
    'kn0bederz',
    'kn0bedes',
    'kn0bedez',
    'kn0beding',
    'kn0bedrs',
    'kn0bedrz',
    'kn0beds',
    'kn0bedz',
    'kn0benders',
    'kn0benderz',
    'kn0bendes',
    'kn0bendez',
    'kn0bending',
    'kn0bendrs',
    'kn0bendrz',
    'kn0bends',
    'kn0bendz',
    'kn0bers',
    'kn0berz',
    'kn0bes',
    'kn0bez',
    'kn0bheaders',
    'kn0bheaderz',
    'kn0bheades',
    'kn0bheadez',
    'kn0bheading',
    'kn0bheadrs',
    'kn0bheadrz',
    'kn0bheads',
    'kn0bheadz',
    'kn0bing',
    'kn0bj0ckyers',
    'kn0bj0ckyerz',
    'kn0bj0ckyes',
    'kn0bj0ckyez',
    'kn0bj0ckying',
    'kn0bj0ckyrs',
    'kn0bj0ckyrz',
    'kn0bj0ckys',
    'kn0bj0ckyz',
    'kn0bj0keyers',
    'kn0bj0keyerz',
    'kn0bj0keyes',
    'kn0bj0keyez',
    'kn0bj0keying',
    'kn0bj0keyrs',
    'kn0bj0keyrz',
    'kn0bj0keys',
    'kn0bj0keyz',
    'kn0brs',
    'kn0brz',
    'kn0bs',
    'kn0bz',
    'knee grow',
    'knob ends',
    'knob heads',
    'knob jockey',
    'knob jockys',
    'knob jokeys',
    'knobbing',
    'knobeads',
    'knobed',
    'knobend',
    'knobhead',
    'knobjocky',
    'knobjokey',
    'kondums',
    'koochess',
    'koochs',
    'koon',
    'kootchs',
    'krappy',
    'krauts',
    'kritarch',
    'kum bubble',
    'kum quat',
    'kumbubble',
    'kumbullbe',
    'kumers',
    'kumerz',
    'kumes',
    'kumez',
    'kuming',
    'kummerers',
    'kummererz',
    'kummeres',
    'kummerez',
    'kummering',
    'kummerrs',
    'kummerrz',
    'kummers',
    'kummerz',
    'kummingers',
    'kummingerz',
    'kumminges',
    'kummingez',
    'kumminging',
    'kummingrs',
    'kummingrz',
    'kummings',
    'kummingz',
    'kumrs',
    'kumrz',
    'kumsers',
    'kumserz',
    'kumses',
    'kumsez',
    'kumsing',
    'kumsrs',
    'kumsrz',
    'kumss',
    'kumsz',
    'kumz',
    'kunilingusers',
    'kunilinguserz',
    'kunilinguses',
    'kunilingusez',
    'kunilingusing',
    'kunilingusrs',
    'kunilingusrz',
    'kunilinguss',
    'kunilingusz',
    'kunters',
    'kunterz',
    'kuntes',
    'kuntez',
    'kunting',
    'kuntrs',
    'kuntrz',
    'kunts',
    'kuntz',
    'kweers',
    'kykes',
    'l!b*',
    'l1b*',
    'l3i+chers',
    'l3i+cherz',
    'l3i+ches',
    'l3i+chez',
    'l3i+ching',
    'l3i+chrs',
    'l3i+chrz',
    'l3i+chs',
    'l3i+chz',
    'l3itchers',
    'l3itcherz',
    'l3itches',
    'l3itchez',
    'l3itching',
    'l3itchrs',
    'l3itchrz',
    'l3itchs',
    'l3itchz',
    'la slimes',
    'la slimez',
    'labiaers',
    'labiaerz',
    'labiaes',
    'labiaez',
    'labiaing',
    'labiars',
    'labiarz',
    'labiaz',
    'lactate',
    'lady boog',
    'lame asss',
    'lameassers',
    'lameasserz',
    'lameasses',
    'lameassez',
    'lameassing',
    'lameassrs',
    'lameassrz',
    'lameasss',
    'lameassz',
    'lap dance',
    'lapdance',
    'lardass',
    'leather restraint',
    'leather straight jacket',
    'lemon party',
    'lesb0ers',
    'lesb0erz',
    'lesb0es',
    'lesb0ez',
    'lesb0ing',
    'lesb0rs',
    'lesb0rz',
    'lesb0s',
    'lesb0z',
    'lesbain',
    'lesbayn',
    'lesbianss',
    'lesbin',
    'lesboss',
    'lez be friends',
    'lezbefriends',
    'lezbianss',
    'lezboss',
    'lezs',
    'lezzieers',
    'lezzieerz',
    'lezziees',
    'lezzieez',
    'lezzieing',
    'lezziers',
    'lezzierz',
    'lezziess',
    'lezziez',
    'lezzo',
    'lezzys',
    'libclowns',
    'libertard',
    'libhole',
    'libt@rds',
    'libtards',
    'libturded',
    'libturds',
    'lick me',
    'lickme',
    'limp dick',
    'limp wristed',
    'limpdick',
    'limy',
    'live sex',
    'livesex',
    'lmfa0ers',
    'lmfa0erz',
    'lmfa0es',
    'lmfa0ez',
    'lmfa0ing',
    'lmfa0rs',
    'lmfa0rz',
    'lmfa0s',
    'lmfa0z',
    'lmfaos',
    'loadedgun',
    'lolis',
    'love goo',
    'love gun',
    'love juice',
    'love muscle',
    'love pistol',
    'love rocket',
    'love your race',
    'lovegoo',
    'lovegun',
    'lovejuice',
    'lovemaking',
    'lovemuscle',
    'lovepistol',
    'loverocket',
    'low life',
    'lowlife',
    'lube job',
    'lubejob',
    'lubricanos',
    'lucky camel toe',
    'luckycammeltoe',
    'm-fuckings',
    'm0-f0ers',
    'm0-f0erz',
    'm0-f0es',
    'm0-f0ez',
    'm0-f0ing',
    'm0-f0rs',
    'm0-f0rz',
    'm0-f0s',
    'm0-f0z',
    'm00lie',
    'm0f0',
    'm0fos',
    'm0thafuckaers',
    'm0thafuckaerz',
    'm0thafuckaes',
    'm0thafuckaez',
    'm0thafuckaing',
    'm0thafuckars',
    'm0thafuckarz',
    'm0thafuckasers',
    'm0thafuckaserz',
    'm0thafuckases',
    'm0thafuckasez',
    'm0thafuckasing',
    'm0thafuckasrs',
    'm0thafuckasrz',
    'm0thafuckass',
    'm0thafuckasz',
    'm0thafuckazers',
    'm0thafuckazerz',
    'm0thafuckazes',
    'm0thafuckazez',
    'm0thafuckazing',
    'm0thafuckazrs',
    'm0thafuckazrz',
    'm0thafuckazs',
    'm0thafuckazz',
    'm0thafucked ers',
    'm0thafucked erz',
    'm0thafucked es',
    'm0thafucked ez',
    'm0thafucked ing',
    'm0thafucked rs',
    'm0thafucked rz',
    'm0thafucked s',
    'm0thafucked z',
    'm0thafuckerers',
    'm0thafuckererz',
    'm0thafuckeres',
    'm0thafuckerez',
    'm0thafuckering',
    'm0thafuckerrs',
    'm0thafuckerrz',
    'm0thafuckersers',
    'm0thafuckerserz',
    'm0thafuckerses',
    'm0thafuckersez',
    'm0thafuckersing',
    'm0thafuckersrs',
    'm0thafuckersrz',
    'm0thafuckerss',
    'm0thafuckersz',
    'm0thafuckerz',
    'm0thafuckes',
    'm0thafuckez',
    'm0thafuckiners',
    'm0thafuckinerz',
    'm0thafuckines',
    'm0thafuckinez',
    'm0thafucking ers',
    'm0thafucking erz',
    'm0thafucking es',
    'm0thafucking ez',
    'm0thafucking ing',
    'm0thafucking rs',
    'm0thafucking rz',
    'm0thafucking s',
    'm0thafucking z',
    'm0thafuckingsers',
    'm0thafuckingserz',
    'm0thafuckingses',
    'm0thafuckingsez',
    'm0thafuckingsing',
    'm0thafuckingsrs',
    'm0thafuckingsrz',
    'm0thafuckingss',
    'm0thafuckingsz',
    'm0thafuckining',
    'm0thafuckinrs',
    'm0thafuckinrz',
    'm0thafuckins',
    'm0thafuckinz',
    'm0thafuckrs',
    'm0thafuckrz',
    'm0thafucksers',
    'm0thafuckserz',
    'm0thafuckses',
    'm0thafucksez',
    'm0thafucksing',
    'm0thafucksrs',
    'm0thafucksrz',
    'm0thafuckss',
    'm0thafucksz',
    'm0thafuckz',
    'm0ther fuckerers',
    'm0ther fuckererz',
    'm0ther fuckeres',
    'm0ther fuckerez',
    'm0ther fuckering',
    'm0ther fuckerrs',
    'm0ther fuckerrz',
    'm0ther fuckers',
    'm0ther fuckerz',
    'm0therfuckeders',
    'm0therfuckederz',
    'm0therfuckedes',
    'm0therfuckedez',
    'm0therfuckeding',
    'm0therfuckedrs',
    'm0therfuckedrz',
    'm0therfuckeds',
    'm0therfuckedz',
    'm0therfuckerers',
    'm0therfuckererz',
    'm0therfuckeres',
    'm0therfuckerez',
    'm0therfuckering',
    'm0therfuckerrs',
    'm0therfuckerrz',
    'm0therfuckersers',
    'm0therfuckerserz',
    'm0therfuckerses',
    'm0therfuckersez',
    'm0therfuckersing',
    'm0therfuckersrs',
    'm0therfuckersrz',
    'm0therfuckerss',
    'm0therfuckersz',
    'm0therfuckerz',
    'm0therfuckes',
    'm0therfuckez',
    'm0therfuckiners',
    'm0therfuckinerz',
    'm0therfuckines',
    'm0therfuckinez',
    'm0therfuckingers',
    'm0therfuckingerz',
    'm0therfuckinges',
    'm0therfuckingez',
    'm0therfuckinging',
    'm0therfuckingrs',
    'm0therfuckingrz',
    'm0therfuckingsers',
    'm0therfuckingserz',
    'm0therfuckingses',
    'm0therfuckingsez',
    'm0therfuckingsing',
    'm0therfuckingsrs',
    'm0therfuckingsrz',
    'm0therfuckingss',
    'm0therfuckingsz',
    'm0therfuckingz',
    'm0therfuckining',
    'm0therfuckinrs',
    'm0therfuckinrz',
    'm0therfuckins',
    'm0therfuckinz',
    'm0therfuckkaers',
    'm0therfuckkaerz',
    'm0therfuckkaes',
    'm0therfuckkaez',
    'm0therfuckkaing',
    'm0therfuckkars',
    'm0therfuckkarz',
    'm0therfuckkas',
    'm0therfuckkaz',
    'm0therfuckrs',
    'm0therfuckrz',
    'm0therfucksers',
    'm0therfuckserz',
    'm0therfuckses',
    'm0therfucksez',
    'm0therfucksing',
    'm0therfucksrs',
    'm0therfucksrz',
    'm0therfuckss',
    'm0therfucksz',
    'm0therfuckz',
    'm45terbate',
    'ma5terb8',
    'ma5terbate',
    'make me come',
    'make me cum',
    'make real cash',
    'mams',
    'man hater',
    'man paste',
    'manhater',
    'manpaste',
    'maricon',
    'mariturds',
    'mary jane',
    'maryjane',
    'mastabater',
    'master blaster',
    'master-bate',
    'masterb8',
    'masterbat*',
    'masterbat3',
    'masterbate',
    'masterbations',
    'masterblaster',
    'mastrabator',
    'masturbate',
    'masturbating',
    'mattress princess',
    'mattressprincess',
    'mcfaggeters',
    'mcfaggeterz',
    'mcfaggetes',
    'mcfaggetez',
    'mcfaggeting',
    'mcfaggetrs',
    'mcfaggetrz',
    'mcfaggets',
    'mcfaggetz',
    'meat beatter',
    'meatbeatter',
    'meine ehre heisst treue',
    'menage a trois',
    'mexi fornia',
    'mexifornia',
    'miggers',
    'miggerz',
    'milf',
    'mingeers',
    'mingeerz',
    'mingees',
    'mingeez',
    'mingeing',
    'mo fos',
    'mof0s',
    'mofos',
    'molester',
    'molestor',
    'money shot',
    'moneyshot',
    'moo-chelle',
    'moochelle',
    'moolies',
    'moonbat',
    'mooselimes',
    'mooselims',
    'mooslims',
    'motha fuckass',
    'motha fuckazs',
    'motha fucked s',
    'motha fuckerss',
    'motha fucking s',
    'motha fuckingss',
    'motha fuckins',
    'motha fuckss',
    'mothafuckass',
    'mothafuckazs',
    'mothafuckeds',
    'mothafuckerss',
    'mothafuckingss',
    'mothafuckins',
    'mothafuckss',
    'mother fuckeds',
    'mother fuckerss',
    'mother fuckingss',
    'mother fuckins',
    'mother fuckkas',
    'mother fuckss',
    'mother humpers',
    'mother love bone',
    'motherf*ckers',
    'motherfucked',
    'motherfuckers',
    'motherfuckings',
    'motherfuckka',
    'motherfucks',
    'motherlovebone',
    'motherufckers',
    'mound of venus',
    'mr hands',
    'mtherfuckers',
    'mthrf*ckers',
    'mthrfuckers',
    'mthrfuckings',
    'muff divers',
    'muff licker',
    'muffdiverers',
    'muffdivererz',
    'muffdiveres',
    'muffdiverez',
    'muffdivering',
    'muffdiverrs',
    'muffdiverrz',
    'muffdivers',
    'muffdiverz',
    'muffdiving',
    'mufferz',
    'muffes',
    'muffez',
    'muffin diver',
    'muffindiver',
    'mufflikcer',
    'muffrs',
    'muffrz',
    'muffz',
    'munging',
    'muslime',
    'mutha feckers',
    'mutha fucker',
    'mutha fuckkers',
    'muthaers',
    'muthaerz',
    'muthaes',
    'muthaez',
    'muthafeckerers',
    'muthafeckererz',
    'muthafeckeres',
    'muthafeckerez',
    'muthafeckering',
    'muthafeckerrs',
    'muthafeckerrz',
    'muthafeckers',
    'muthafeckerz',
    'muthafuckazs',
    'muthafuckers',
    'muthafuckkerers',
    'muthafuckkererz',
    'muthafuckkeres',
    'muthafuckkerez',
    'muthafuckkering',
    'muthafuckkerrs',
    'muthafuckkerrz',
    'muthafuckkers',
    'muthafuckkerz',
    'muthaing',
    'muthars',
    'mutharz',
    'muthas',
    'muthaz',
    'muther fuckers',
    'mutherers',
    'muthererz',
    'mutheres',
    'mutherez',
    'mutherfuckerers',
    'mutherfuckererz',
    'mutherfuckeres',
    'mutherfuckerez',
    'mutherfuckering',
    'mutherfuckerrs',
    'mutherfuckerrz',
    'mutherfuckers',
    'mutherfuckerz',
    'mutherfuckings',
    'muthering',
    'mutherrs',
    'mutherrz',
    'muthers',
    'mutherz',
    'muthrfuckings',
    'muzzies',
    'muzziez',
    'my honor is loyalty',
    'n!gger',
    'n*ggers',
    'n0b j0keyers',
    'n0b j0keyerz',
    'n0b j0keyes',
    'n0b j0keyez',
    'n0b j0keying',
    'n0b j0keyrs',
    'n0b j0keyrz',
    'n0b j0keys',
    'n0b j0keyz',
    'n1ggaers',
    'n1ggaerz',
    'n1ggaes',
    'n1ggaez',
    'n1ggaing',
    'n1ggars',
    'n1ggarz',
    'n1ggas',
    'n1ggaz',
    'n1ggerers',
    'n1ggererz',
    'n1ggeres',
    'n1ggerez',
    'n1ggering',
    'n1ggerrs',
    'n1ggerrz',
    'n1ggers',
    'n1ggerz',
    'nambla',
    'nasty bitch',
    'nasty ho',
    'nasty slut',
    'nasty whore',
    'nastybitch',
    'nastyho',
    'nastyslut',
    'nastywhore',
    'nawashi',
    'neggar',
    'neggers',
    'negroids',
    'neon deon',
    'newsbusters',
    'ni99ah',
    'ni99ar',
    'ni99er',
    'ni99ur',
    'nig nog',
    'nigaboo',
    'nigars',
    'nigarz',
    'nigerz',
    'nigettes',
    'nigg3rers',
    'nigg3rerz',
    'nigg3res',
    'nigg3rez',
    'nigg3ring',
    'nigg3rrs',
    'nigg3rrz',
    'nigg3rs',
    'nigg3rz',
    'nigg4hers',
    'nigg4herz',
    'nigg4hes',
    'nigg4hez',
    'nigg4hing',
    'nigg4hrs',
    'nigg4hrz',
    'nigg4hs',
    'nigg4hz',
    'niggaers',
    'niggaerz',
    'niggaes',
    'niggaez',
    'niggahers',
    'niggaherz',
    'niggahes',
    'niggahez',
    'niggahing',
    'niggahrs',
    'niggahrz',
    'niggahs',
    'niggahz',
    'niggaing',
    'niggars',
    'niggarz',
    'niggasers',
    'niggaserz',
    'niggases',
    'niggasez',
    'niggasing',
    'niggasrs',
    'niggasrz',
    'niggass',
    'niggasz',
    'niggazers',
    'niggazerz',
    'niggazes',
    'niggazez',
    'niggazing',
    'niggazrs',
    'niggazrz',
    'niggazs',
    'niggazz',
    'niggerers',
    'niggererz',
    'niggeres',
    'niggerez',
    'niggering',
    'niggerrs',
    'niggerrz',
    'niggers ers',
    'niggers erz',
    'niggers es',
    'niggers ez',
    'niggers ing',
    'niggers rs',
    'niggers rz',
    'niggers s',
    'niggers z',
    'niggerz',
    'niggies',
    'niggresses',
    'niggressez',
    'nigguhs',
    'nigguhz',
    'niggurs',
    'niggurz',
    'niglet',
    'nigors',
    'nigorz',
    'nigras',
    'nigraz',
    'nigres',
    'nigrettes',
    'nigrez',
    'nigz',
    'nimphomania',
    'nipple ring',
    'nipplering',
    'nit tit',
    'nittit',
    'no fucking way',
    'no sex',
    'nobheads',
    'nobjockys',
    'nobjokeys',
    'nofuckingway',
    'non silba sed anthar',
    'nookie',
    'nooner',
    'nsfw images',
    'nssa',
    'nucking futss',
    'numb nutss',
    'numbnutsers',
    'numbnutserz',
    'numbnutses',
    'numbnutsez',
    'numbnutsing',
    'numbnutsrs',
    'numbnutsrz',
    'numbnutss',
    'numbnutsz',
    'nut fucker',
    'nut sackers',
    'nut sackerz',
    'nut sackes',
    'nut sackez',
    'nut sacking',
    'nut sackrs',
    'nut sackrz',
    'nut sacks',
    'nut sackz',
    'nutfucker',
    'nutsackers',
    'nutsackerz',
    'nutsackes',
    'nutsackez',
    'nutsacking',
    'nutsackrs',
    'nutsackrz',
    'nutsacks',
    'nutsackz',
    'nymphomania',
    'o-bammy',
    'o-bozo',
    'o-bummer',
    'o-zero',
    'obammy',
    'obozo',
    'obumer',
    'obummer',
    'octopussy',
    'ofof',
    'oicu812',
    'omorashi',
    'on the rag',
    'one cup two girls',
    'one guy one jar',
    'ontherag',
    'orgasims',
    'ou812',
    'outlookcom',
    'ozero',
    'p i m p',
    'p o s',
    'p.u.s.s.y.s',
    'p00naniers',
    'p00nanierz',
    'p00nanies',
    'p00naniez',
    'p00naniing',
    'p00nanirs',
    'p00nanirz',
    'p00nanis',
    'p00naniz',
    'p00nanyers',
    'p00nanyerz',
    'p00nanyes',
    'p00nanyez',
    'p00nanying',
    'p00nanyrs',
    'p00nanyrz',
    'p00nanys',
    'p00nanyz',
    'p00ners',
    'p00nerz',
    'p00nes',
    'p00nez',
    'p00ning',
    'p00nrs',
    'p00nrz',
    'p00ns',
    'p00ntangers',
    'p00ntangerz',
    'p00ntanges',
    'p00ntangez',
    'p00ntanging',
    'p00ntangrs',
    'p00ntangrz',
    'p00ntangs',
    'p00ntangz',
    'p00nz',
    'p00pers',
    'p00perz',
    'p00pes',
    'p00pez',
    'p00ping',
    'p00prs',
    'p00prz',
    'p00ps',
    'p00pz',
    'p0lesm0kerers',
    'p0lesm0kererz',
    'p0lesm0keres',
    'p0lesm0kerez',
    'p0lesm0kering',
    'p0lesm0kerrs',
    'p0lesm0kerrz',
    'p0lesm0kers',
    'p0lesm0kerz',
    'p0rn',
    'paedophile',
    'pakies',
    'pakiez',
    'pakis',
    'pan00chers',
    'pan00cherz',
    'pan00ches',
    'pan00chez',
    'pan00ching',
    'pan00chrs',
    'pan00chrz',
    'pan00chs',
    'pan00chz',
    'panoochs',
    'pearlnecklace',
    'pecker heads',
    'peckerers',
    'peckererz',
    'peckeres',
    'peckerez',
    'peckerheaders',
    'peckerheaderz',
    'peckerheades',
    'peckerheadez',
    'peckerheading',
    'peckerheadrs',
    'peckerheadrz',
    'peckerheads',
    'peckerheadz',
    'peckering',
    'peckerrs',
    'peckerrz',
    'peckers',
    'peckerwood',
    'peckerz',
    'pedobear',
    'pedophile',
    'pee o ess',
    'peepshow',
    'peepshpw',
    'pegging',
    'pencilneck',
    'penis fuckers',
    'penis puffers',
    'penisbanger',
    'penisfuckerers',
    'penisfuckererz',
    'penisfuckeres',
    'penisfuckerez',
    'penisfuckering',
    'penisfuckerrs',
    'penisfuckerrz',
    'penisfuckers',
    'penisfuckerz',
    'penising',
    'penispufferers',
    'penispuffererz',
    'penispufferes',
    'penispufferez',
    'penispuffering',
    'penispufferrs',
    'penispufferrz',
    'penispuffers',
    'penispufferz',
    'phaggot',
    'phone sex',
    'phque',
    'phuck',
    'phukeders',
    'phukederz',
    'phukedes',
    'phukedez',
    'phukeding',
    'phukedrs',
    'phukedrz',
    'phukeds',
    'phukedz',
    'phukers',
    'phukerz',
    'phukes',
    'phukez',
    'phukingers',
    'phukingerz',
    'phukinges',
    'phukingez',
    'phukinging',
    'phukingrs',
    'phukingrz',
    'phukings',
    'phukingz',
    'phukkeders',
    'phukkederz',
    'phukkedes',
    'phukkedez',
    'phukkeding',
    'phukkedrs',
    'phukkedrz',
    'phukkeds',
    'phukkedz',
    'phukkingers',
    'phukkingerz',
    'phukkinges',
    'phukkingez',
    'phukkinging',
    'phukkingrs',
    'phukkingrz',
    'phukkings',
    'phukkingz',
    'phuks',
    'phuqers',
    'phuqerz',
    'phuqes',
    'phuqez',
    'phuqing',
    'phuqqing',
    'phuqrs',
    'phuqrz',
    'phuqs',
    'phuqz',
    'piece of shit',
    'pig fuckers',
    'pigfuckerers',
    'pigfuckererz',
    'pigfuckeres',
    'pigfuckerez',
    'pigfuckering',
    'pigfuckerrs',
    'pigfuckerrz',
    'pigfuckers',
    'pigfuckerz',
    'pillowbiters',
    'pimp simp',
    'pimped',
    'pimper',
    'pimpis',
    'pimpjuice',
    'pimpsimp',
    'pinche mayate',
    'pinchy mai-yah-te',
    'piss head',
    'piss pig',
    'pissed',
    'pissers',
    'pisses',
    'pissflaps',
    'pisshead',
    'pissing',
    'pissoff',
    'pisspig',
    'pleasure chest',
    'pocket pool',
    'pocketpool',
    'polacks',
    'pole smokers',
    'polesmokers',
    'ponyplay',
    'poon tang',
    'poonanis',
    'poonanys',
    'poons',
    'poontangs',
    'poop chute',
    'poop pushers',
    'poopchute',
    'pooppushers',
    'poor white trash',
    'poorwhitetrash',
    'popimp',
    'porch monkeyss',
    'porchmonkey',
    'porn flick',
    'porn king',
    'porn princess',
    'pornflick',
    'pornking',
    'porno',
    'pornprincess',
    'pornz',
    'prick head',
    'prickhead',
    'primetime',
    'prince albert piercing',
    'prns',
    'prnz',
    'pron',
    'pthc',
    'pu$$ys',
    'pubeers',
    'pubeerz',
    'pubees',
    'pubeez',
    'pubeing',
    'pubes',
    'pubic lice',
    'pubiclice',
    'pud boy',
    'pudboy',
    'pudd boy',
    'puddboy',
    'pun tang',
    'punannyers',
    'punannyerz',
    'punannyes',
    'punannyez',
    'punannying',
    'punannyrs',
    'punannyrz',
    'punannys',
    'punannyz',
    'punany',
    'puntaers',
    'puntaerz',
    'puntaes',
    'puntaez',
    'puntaing',
    'puntang',
    'purina princess',
    'purinapricness',
    'pusseers',
    'pusseerz',
    'pussees',
    'pusseez',
    'pusseing',
    'pussers',
    'pusserz',
    'pusses',
    'pussez',
    'pussiers',
    'pussierz',
    'pussiesers',
    'pussieserz',
    'pussieses',
    'pussiesez',
    'pussiesing',
    'pussiesrs',
    'pussiesrz',
    'pussiess',
    'pussiesz',
    'pussiez',
    'pussiing',
    'pussirs',
    'pussirz',
    'pussis',
    'pussiz',
    'pusss',
    'pussy cat',
    'pussy eater',
    'pussy fucker',
    'pussy licker',
    'pussy lickings',
    'pussy lips',
    'pussy lover',
    'pussy pounder',
    'pussyeater',
    'pussyers',
    'pussyerz',
    'pussyes',
    'pussyez',
    'pussyfucker',
    'pussying',
    'pussylicker',
    'pussylickingers',
    'pussylickingerz',
    'pussylickinges',
    'pussylickingez',
    'pussylickinging',
    'pussylickingrs',
    'pussylickingrz',
    'pussylickings',
    'pussylickingz',
    'pussylips',
    'pussylover',
    'pussypounders',
    'pussys',
    'putt pirate',
    'puzzy',
    'pwt',
    'queafs',
    'queefers',
    'queeferz',
    'queefes',
    'queefez',
    'queefing',
    'queefrs',
    'queefrz',
    'queefs',
    'queefz',
    'queer baits',
    'queer holes',
    'queerbaiters',
    'queerbaiterz',
    'queerbaites',
    'queerbaitez',
    'queerbaiting',
    'queerbaitrs',
    'queerbaitrz',
    'queerbaits',
    'queerbaitz',
    'queerh0leers',
    'queerh0leerz',
    'queerh0lees',
    'queerh0leez',
    'queerh0leing',
    'queerh0lers',
    'queerh0lerz',
    'queerh0les',
    'queerh0lez',
    'queerholes',
    'queeros',
    'queerss',
    'quickie',
    'quims',
    'r-tards',
    'rag head',
    'rag-heads',
    'ragheads',
    'raging boner',
    'rahowa',
    're tarded',
    'rear end',
    'rear entry',
    'rearend',
    'rearentry',
    'rectumers',
    'rectumerz',
    'rectumes',
    'rectumez',
    'rectuming',
    'rectumrs',
    'rectumrz',
    'reefer',
    'reetards',
    'ren0bers',
    'ren0berz',
    'ren0bes',
    'ren0bez',
    'ren0bing',
    'ren0brs',
    'ren0brz',
    'ren0bs',
    'ren0bz',
    'renobs',
    'rent a fuck',
    'rentafuck',
    'reptard',
    'republicons',
    'republicunt',
    'republikkkans',
    'repignicrats',
    'repukes',
    'retardeds',
    'retarderz',
    'retardes',
    'retardez',
    'retardin',
    'retardrs',
    'retardrz',
    'retards',
    'retardz',
    'reverse cowgirl',
    'ribbed',
    'rim jobss',
    'rimj0bers',
    'rimj0berz',
    'rimj0bes',
    'rimj0bez',
    'rimj0bing',
    'rimj0brs',
    'rimj0brz',
    'rimj0bs',
    'rimj0bz',
    'rimjawers',
    'rimjawerz',
    'rimjawes',
    'rimjawez',
    'rimjawing',
    'rimjawrs',
    'rimjawrz',
    'rimjaws',
    'rimjawz',
    'rimjobs',
    'rimmingers',
    'rimmingerz',
    'rimminges',
    'rimmingez',
    'rimminging',
    'rimmingrs',
    'rimmingrz',
    'rimmings',
    'rimmingz',
    'ritards',
    'robber',
    'roflmao',
    'rosy palm and her 5 sisters',
    'rot in hell',
    'rtards',
    'rumprammers',
    'rusty trombone',
    's and m',
    's h i t',
    's hiters',
    's hiterz',
    's hites',
    's hitez',
    's hiting',
    's hitrs',
    's hitrz',
    's hits',
    's hitz',
    's-h-1-ts',
    's-h-i-ts',
    's-o-bs',
    's.0.b.ers',
    's.0.b.erz',
    's.0.b.es',
    's.0.b.ez',
    's.0.b.ing',
    's.0.b.rs',
    's.0.b.rz',
    's.0.b.s',
    's.0.b.z',
    's.h.i.t.s',
    's.j.w.',
    's.o.b.s',
    's**t',
    's&m',
    's0bs',
    's0n-0f-a-bitchers',
    's0n-0f-a-bitcherz',
    's0n-0f-a-bitches',
    's0n-0f-a-bitchez',
    's0n-0f-a-bitching',
    's0n-0f-a-bitchrs',
    's0n-0f-a-bitchrz',
    's0n-0f-a-bitchs',
    's0n-0f-a-bitchz',
    'sadism',
    'samckdaddy',
    'sand niggerss',
    'sandm',
    'sandnigger',
    'santorum',
    'scat',
    'schitface',
    'schitstain',
    'schittt',
    'schlong',
    'schwarze sonne',
    'scissoring',
    'screw you',
    'screwyou',
    'scroat',
    'scrote',
    'scrotum',
    'semen',
    'separate place for every race',
    'sex farm',
    'sex hound',
    'sex house',
    'sex kitten',
    'sex pot',
    'sex slave',
    'sex to go',
    'sex whore',
    'sexfarm',
    'sexhound',
    'sexhouse',
    'sexkitten',
    'sexo',
    'sexpot',
    'sexslave',
    'sextogo',
    'sexwhore',
    'sexy biatch',
    'sexy bitch',
    'sexy moma',
    'sexy slim',
    'sexymoma',
    'sh__hole',
    'sh!+ers',
    'sh!+erz',
    'sh!+es',
    'sh!+ez',
    'sh!+ing',
    'sh!+rs',
    'sh!+rz',
    'sh!+s',
    'sh!+z',
    'sh!ters',
    'sh!terz',
    'sh!tes',
    'sh!tez',
    'sh!ting',
    'sh!trs',
    'sh!trz',
    'sh!ts',
    'sh!tz',
    'sh1ters',
    'sh1terz',
    'sh1tes',
    'sh1tez',
    'sh1ting',
    'sh1trs',
    'sh1trz',
    'sh1ts',
    'sh1tz',
    'shagers',
    'shagerz',
    'shages',
    'shagez',
    'shaggerers',
    'shaggererz',
    'shaggeres',
    'shaggerez',
    'shaggering',
    'shaggerrs',
    'shaggerrz',
    'shaggers',
    'shaggerz',
    'shagginers',
    'shagginerz',
    'shaggines',
    'shagginez',
    'shaggingers',
    'shaggingerz',
    'shagginges',
    'shaggingez',
    'shagginging',
    'shaggingrs',
    'shaggingrz',
    'shaggings',
    'shaggingz',
    'shaggining',
    'shagginrs',
    'shagginrz',
    'shaggins',
    'shagginz',
    'shamedames',
    'shaved beaver',
    'shaved pussy',
    'shawtypimp',
    'she males',
    'shemaleers',
    'shemaleerz',
    'shemalees',
    'shemaleez',
    'shemaleing',
    'shemalers',
    'shemalerz',
    'shemales',
    'shemalez',
    'shi tty',
    'shi+',
    'shiathole',
    'shibari',
    'shiiit',
    'shiit*',
    'shiithole',
    'shit dick',
    'shit eater',
    'shit face',
    'shit for brains',
    'shit fucker',
    'shit happens',
    'shit head',
    'shit out of luck',
    'shit stain',
    'shit4brains',
    'shitass',
    'shitbagger',
    'shitbags',
    'shitblimp',
    'shitbrains',
    'shitbreath',
    'shitcanned',
    'shitcunt',
    'shitdick',
    'shiteater',
    'shited',
    'shitey',
    'shitfaced',
    'shitforbrains',
    'shitfucker',
    'shitfull',
    'shitgibbon',
    'shithapens',
    'shithappens',
    'shitholes',
    'shithouse',
    'shitings',
    'shitless',
    'shitoutofluck',
    'shitpost',
    'shitspitter',
    'shitstain',
    'shitted',
    'shitters',
    'shitthole',
    'shittiest',
    'shittings',
    'shitty',
    'shiznit',
    'shjjt',
    'shjt',
    'short fuck',
    'shortfuck',
    'shota',
    'showtime',
    'shrillary',
    'shrimping',
    'sieg heil',
    'six six six',
    'sixsixsix',
    'sixty 9',
    'sixty nine',
    'sixtynine',
    'sjw',
    'skank bitch',
    'skank fuck',
    'skank whore',
    'skankbitch',
    'skankfuck',
    'skankwhore',
    'skanky bitch',
    'skanky whore',
    'skankybitch',
    'skankywhore',
    'skeeterz',
    'skeetes',
    'skeetez',
    'skeetin',
    'skeetrs',
    'skeetrz',
    'skeets',
    'skeetz',
    'skin flute',
    'skinflute',
    'skullfuck',
    'skum bag',
    'skumbag',
    'slant eye',
    'slanteye',
    'slave driver',
    'slavedriver',
    'sleeze bag',
    'sleeze ball',
    'sleezebag',
    'sleezeball',
    'slide it in',
    'slideitin',
    'slime bucket',
    'slimeball',
    'slimebucket',
    'slut wear',
    'slut whore',
    'slutbag',
    'slutting',
    'slutty',
    'slutwear',
    'slutwhore',
    'smack daddy',
    'smack the monkey',
    'smackthemonkey',
    'smagma',
    'smart ass',
    'smegers',
    'smegerz',
    'smeges',
    'smegez',
    'smeghead',
    'smeging',
    'smegmaers',
    'smegmaerz',
    'smegmaes',
    'smegmaez',
    'smegmaing',
    'smegmars',
    'smegmarz',
    'smegmas',
    'smegmaz',
    'smegrs',
    'smegrz',
    'smegs',
    'smegz',
    'smuters',
    'smuterz',
    'smutes',
    'smutez',
    'smuting',
    'smutrs',
    'smutrz',
    'smuts',
    'smuttys',
    'smutz',
    'snatch patch',
    'snatcherz',
    'snatches',
    'snatchez',
    'snatchin',
    'snatchpatch',
    'snatchrs',
    'snatchrz',
    'snatchs',
    'snatchz',
    'snowballing',
    'sobs',
    'sodomite',
    'sodomize',
    'sodoms',
    'sodomy',
    'son of a bitch',
    'son-of-a-bitchs',
    'son0f a bitchs',
    'sonnenrad',
    'sonofabitchs',
    'sonofbitch',
    'spank the monkey',
    'spankthemonkey',
    'sperm bag',
    'sperm hearder',
    'sperm herder',
    'spermacide',
    'spermbag',
    'spermhearder',
    'spermherder',
    'spicks',
    'spickz',
    'spics',
    'spicz',
    'spigz',
    'spikss',
    'spikz',
    'spl00geers',
    'spl00geerz',
    'spl00gees',
    'spl00geez',
    'spl00geing',
    'spl00gers',
    'spl00gerz',
    'spl00ges',
    'spl00gez',
    'split tail',
    'split tial',
    'splittail',
    'splooge moose',
    'splooges',
    'spooges',
    'spread legs',
    'spunkers',
    'spunkerz',
    'spunkes',
    'spunkez',
    'spunking',
    'spunkrs',
    'spunkrz',
    'spunks',
    'spunkz',
    'stagg',
    'stfus',
    'stiffys',
    'strap on',
    'strapon',
    'strappado',
    'stringer',
    'strip club',
    'stripclub',
    'stupid fucker',
    'stupidfucker',
    'style doggy',
    'suck asss',
    'suck dick',
    'suck me',
    'suck my ass',
    'suck my dick',
    'suck my tit',
    'suck off',
    'suckassers',
    'suckasserz',
    'suckasses',
    'suckassez',
    'suckassing',
    'suckassrs',
    'suckassrz',
    'suckasss',
    'suckassz',
    'suckdick',
    'suckme',
    'suckmyass',
    'suckmydick',
    'suckmytit',
    'suckoff',
    'suicide girls',
    'sultry women',
    'swallower',
    'swalow',
    'sweetness',
    'swign dixx',
    'swing dixx',
    'swinger',
    'swingin dixx',
    'swinging dicks',
    'syphilis',
    't bggrs',
    't1tt1e5',
    't1tties',
    'tainted love',
    'taste my',
    'tawdrys',
    'tea baggers',
    'tea bagging',
    'tea-bags',
    'teabaggers',
    'teabaggings',
    'teetserz',
    'teetses',
    'teetsez',
    'teetsing',
    'teetsrs',
    'teetsrz',
    'teetss',
    'teetsz',
    'teezers',
    'teezerz',
    'teezes',
    'teezez',
    'teezing',
    'teezrs',
    'teezrz',
    'teezs',
    'teezz',
    'terds',
    'testees',
    'testess',
    'testicalers',
    'testicalerz',
    'testicalez',
    'testicaling',
    'testicalrs',
    'testicalrz',
    'testicalz',
    'testicleers',
    'testicleerz',
    'testiclees',
    'testicleez',
    'testicleing',
    'testiclers',
    'testiclerz',
    'testiclez',
    'the existence of our people',
    'third eye',
    'third leg',
    'thirdeye',
    'thirdleg',
    'three some',
    'threesome',
    'throating',
    'thunder cunts',
    'thundercunters',
    'thundercunterz',
    'thundercuntes',
    'thundercuntez',
    'thundercunting',
    'thundercuntrs',
    'thundercuntrz',
    'thundercunts',
    'thundercuntz',
    'timas',
    'tinyurl',
    'tit bit nipply',
    'tit fucker',
    'tit fuckin',
    'tit fucks',
    'tit job',
    'tit licker',
    'tit lover',
    'tit wanks',
    'titbitnipply',
    'titers',
    'titerz',
    'tites',
    'titez',
    'titfuckers',
    'titfuckerz',
    'titfuckes',
    'titfuckez',
    'titfucking',
    'titfuckrs',
    'titfuckrz',
    'titfucks',
    'titfuckz',
    'titing',
    'titis',
    'titjob',
    'titlicker',
    'titlover',
    'titrs',
    'titrz',
    'titsers',
    'titserz',
    'titses',
    'titsez',
    'titsing',
    'titsrs',
    'titsrz',
    'titss',
    'titsz',
    'titterz',
    'tittes',
    'tittez',
    'tittie fuckers',
    'tittie5ers',
    'tittie5erz',
    'tittie5es',
    'tittie5ez',
    'tittie5ing',
    'tittie5rs',
    'tittie5rz',
    'tittie5s',
    'tittie5z',
    'tittiefuckerers',
    'tittiefuckererz',
    'tittiefuckeres',
    'tittiefuckerez',
    'tittiefuckering',
    'tittiefuckerrs',
    'tittiefuckerrz',
    'tittiefuckers',
    'tittiefuckerz',
    'tittiesers',
    'tittieserz',
    'tittieses',
    'tittiesez',
    'tittiesing',
    'tittiesrs',
    'tittiesrz',
    'tittiess',
    'tittiesz',
    'titting',
    'tittrs',
    'tittrz',
    'titts',
    'titty fucks',
    'titty wanks',
    'tittyfuckers',
    'tittyfuckerz',
    'tittyfuckes',
    'tittyfuckez',
    'tittyfucking',
    'tittyfuckrs',
    'tittyfuckrz',
    'tittyfucks',
    'tittyfuckz',
    'tittys',
    'tittywankers',
    'tittywankerz',
    'tittywankes',
    'tittywankez',
    'tittywanking',
    'tittywankrs',
    'tittywankrz',
    'tittywanks',
    'tittywankz',
    'tittz',
    'titwankers',
    'titwankerz',
    'titwankes',
    'titwankez',
    'titwanking',
    'titwankrs',
    'titwankrz',
    'titwanks',
    'titwankz',
    'titz',
    'tongethruster',
    'tongue in a',
    'tongue thruster',
    'tongue tramp',
    'tonguethrust',
    'tonguetramp',
    'topless',
    'tossers',
    'toung thruster',
    'tounge baller',
    'tounge thrust',
    'towel heads',
    'towelheads',
    'trailer trash',
    'trailertrash',
    'trannies',
    'trannys',
    'trashys',
    'tri sexual',
    'tribadism',
    'triple x',
    'triplex',
    'trisexual',
    'triskele',
    'trots',
    'trumpanzee',
    'tub girl',
    'tubgirls',
    'tunnel of love',
    'tunneloflove',
    'turdds',
    'turders',
    'turderz',
    'turdes',
    'turdez',
    'turding',
    'turdrs',
    'turdrz',
    'turdss',
    'turdz',
    'turrds',
    'tushy',
    'tw4ters',
    'tw4terz',
    'tw4tes',
    'tw4tez',
    'tw4ting',
    'tw4trs',
    'tw4trz',
    'tw4ts',
    'tw4tz',
    'twat heads',
    'twat lipss',
    'twat waffles',
    'twaters',
    'twaterz',
    'twates',
    'twatez',
    'twatheaders',
    'twatheaderz',
    'twatheades',
    'twatheadez',
    'twatheading',
    'twatheadrs',
    'twatheadrz',
    'twatheads',
    'twatheadz',
    'twating',
    'twatlipsers',
    'twatlipserz',
    'twatlipses',
    'twatlipsez',
    'twatlipsing',
    'twatlipsrs',
    'twatlipsrz',
    'twatlipss',
    'twatlipsz',
    'twatrs',
    'twatrz',
    'twatsers',
    'twatserz',
    'twatses',
    'twatsez',
    'twatsing',
    'twatsrs',
    'twatsrz',
    'twatss',
    'twatsz',
    'twattyers',
    'twattyerz',
    'twattyes',
    'twattyez',
    'twattying',
    'twattyrs',
    'twattyrz',
    'twattys',
    'twattyz',
    'twatwaffleers',
    'twatwaffleerz',
    'twatwafflees',
    'twatwaffleez',
    'twatwaffleing',
    'twatwafflers',
    'twatwafflerz',
    'twatwaffles',
    'twatwafflez',
    'twatz',
    'twinkie',
    'two bit whore',
    'two girls one cup',
    'twobitwhore',
    'twunterers',
    'twuntererz',
    'twunteres',
    'twunterez',
    'twuntering',
    'twunterrs',
    'twunterrz',
    'twunters',
    'twunterz',
    'twuntes',
    'twuntez',
    'twunting',
    'twuntrs',
    'twuntrz',
    'twunts',
    'twuntz',
    'uncle fuckers',
    'unclefuckerers',
    'unclefuckererz',
    'unclefuckeres',
    'unclefuckerez',
    'unclefuckering',
    'unclefuckerrs',
    'unclefuckerrz',
    'unclefuckers',
    'unclefuckerz',
    'undressing',
    'unfuckable',
    'up the ass',
    'up the butt',
    'upskirt',
    'uptheass',
    'upthebutt',
    'ur garbage',
    'ur trash',
    'urethra play',
    'urinate',
    'urophilia',
    'v14graers',
    'v14graerz',
    'v14graes',
    'v14graez',
    'v14graing',
    'v14grars',
    'v14grarz',
    'v14gras',
    'v14graz',
    'v1graers',
    'v1graerz',
    'v1graes',
    'v1graez',
    'v1graing',
    'v1grars',
    'v1grarz',
    'v1gras',
    'v1graz',
    'va-j-j',
    'vaginaers',
    'vaginaerz',
    'vaginaes',
    'vaginaez',
    'vaginaing',
    'vaginars',
    'vaginarz',
    'vaginaz',
    'vags',
    'vajayjayers',
    'vajayjayerz',
    'vajayjayes',
    'vajayjayez',
    'vajayjaying',
    'vajayjayrs',
    'vajayjayrz',
    'vajayjays',
    'vajayjayz',
    'venus mound',
    'viagraers',
    'viagraerz',
    'viagraes',
    'viagraez',
    'viagraing',
    'viagrars',
    'viagrarz',
    'viagraz',
    'vibrator',
    'violet wand',
    'virgin breaker',
    'virginbreaker',
    'vjayjay',
    'vorarephilia',
    'voyeur',
    'vulvaers',
    'vulvaerz',
    'vulvaes',
    'vulvaez',
    'vulvaing',
    'vulvars',
    'vulvarz',
    'vulvaz',
    'w@ngs',
    'w*t back',
    'w*tb*cc',
    'w*tb*kc',
    'w*tb*kk',
    'w*tback',
    'w00seers',
    'w00seerz',
    'w00sees',
    'w00seez',
    'w00seing',
    'w00sers',
    'w00serz',
    'w00ses',
    'w00sez',
    'w8ss',
    'wangerz',
    'wanges',
    'wangez',
    'wanging',
    'wangrs',
    'wangrz',
    'wangs',
    'wangz',
    'wankerers',
    'wankererz',
    'wankeres',
    'wankerez',
    'wankering',
    'wankerrs',
    'wankerrz',
    'wankjob',
    'wankyers',
    'wankyerz',
    'wankyes',
    'wankyez',
    'wankying',
    'wankyrs',
    'wankyrz',
    'wankys',
    'wankyz',
    'waysted',
    'wet b*ck',
    'wet backs',
    'wet spot',
    'wetb*ck',
    'wetbacks',
    'wetbackz',
    'wetspot',
    'wh0arers',
    'wh0arerz',
    'wh0ares',
    'wh0arez',
    'wh0aring',
    'wh0arrs',
    'wh0arrz',
    'wh0ars',
    'wh0arz',
    'wh0r3f@ces',
    'wh0rebagers',
    'wh0rebagerz',
    'wh0rebages',
    'wh0rebagez',
    'wh0rebaging',
    'wh0rebagrs',
    'wh0rebagrz',
    'wh0rebags',
    'wh0rebagz',
    'wh0reers',
    'wh0reerz',
    'wh0rees',
    'wh0reez',
    'wh0ref@ces',
    'wh0refaceers',
    'wh0refaceerz',
    'wh0refacees',
    'wh0refaceez',
    'wh0refaceing',
    'wh0refacers',
    'wh0refacerz',
    'wh0refaces',
    'wh0refacez',
    'wh0reing',
    'wh0rers',
    'wh0rerz',
    'wh0res',
    'wh0rez',
    'whack0ffs',
    'whacked0ffs',
    'whacker',
    'whacking0ffs',
    'whiskey dick',
    'whiskeydick',
    'whisky dick',
    'whiskydick',
    'white children',
    'white power',
    'whiteys',
    'whizs',
    'whoars',
    'whoraliciouss',
    'whore bags',
    'whore faces',
    'whore fucker',
    'whore house',
    'whorealiciouss',
    'whorebags',
    'whoreds',
    'whorefaces',
    'whorefucker',
    'whorehoppers',
    'whorehouse',
    'whoress',
    'whorings',
    'wiggers',
    'willie wanker',
    'williesers',
    'willieserz',
    'willieses',
    'williesez',
    'williesing',
    'williesrs',
    'williesrz',
    'williess',
    'williesz',
    'williewanker',
    'willyers',
    'willyerz',
    'willyes',
    'willyez',
    'willying',
    'willyrs',
    'willyrz',
    'willys',
    'willyz',
    'wolfsangel',
    'woodys',
    'wops',
    'wpww',
    'wrapping men',
    'wrinkled starfish',
    'wtfs',
    'wuutang',
    'x-rateds',
    'xrateders',
    'xratederz',
    'xratedes',
    'xratedez',
    'xrateding',
    'xratedrs',
    'xratedrz',
    'xrateds',
    'xxxers',
    'xxxerz',
    'xxxin',
    'xxxrs',
    'xxxrz',
    'xxxs',
    'yaoi',
    'yeastys',
    'yellow man',
    'yellow showers',
    'yellowman',
    'yid',
    'yiffy',
    "you're garbage",
    'youre trash',
    'zibbi',
    'zog',
    'zoophilia',
    '***k off',
    'abos',
    'bastards',
    'c**t',
    'corrupt',
    'corupt',
    'coward',
    'd/head',
    'dickhed',
    'donelly',
    'donnelly',
    'donnely',
    'f%$king',
    "f'n",
    'f**k',
    'fack',
    'faggott',
    'fagott',
    'faqed',
    'farked',
    'farking',
    'fcucn',
    'feckin',
    'fgt',
    'filthy',
    'fk in',
    'fkn',
    'for fs',
    'fore fs',
    'ftp',
    'fu*k',
    'fuckery',
    'fukd',
    'fuked',
    'fuken',
    'fukn',
    'fukt',
    'guilty',
    'gypo',
    'idiots',
    'islamic',
    'kockhead',
    'kuntwit',
    'loonies',
    'meth',
    'morons',
    'moslem',
    'muthfucker',
    'niggarism',
    'piss off',
    'poofters',
    'pricks',
    'pusey',
    'pussey',
    'puzzey',
    'rayney',
    'scum bags',
    'scumbags',
    'scums',
    'sears',
    'shitheads',
]
